packages/x6/src/dom/util/style.ts
add cache to Close #116
add timestamp  and  hasScrollbars bool value to dom container to avoid browser  dom layout  reflo in 500ms threshold. 
500ms 内只查询一次dom  来判断hasScrollbars
=> add cache to  fix #116 performace issue 

.gitignore, examples/x6-example-features/src/pages/react/portal.tsx, packages/x6-react-shape/src/portal.ts
Typo `getPovider` in `x6-react-shape` Portal API.
* fix: in the `packages/x6-react-shape/src/portal.ts`, API name `getPovider` should be `getProvider`.
* chore: add `.idea` to `.gitignore` for jetbrains IDE
=> Fix: typo "getPovider" in "portal" of x6-react-shape

packages/x6/src/addon/scroller/index.ts
batch:stop 事件之后也触发一次update，解决移动节点后计算 contentarea 使用的是之前的 area
=> fix: add trigger point for update in scroller

packages/x6-react-components/src/menubar/item.tsx
问题： 快速切换item 会出现重复的 弹框
原因：isPrevMenuHiddening 函数为true 即上个菜单正在关闭时候 onMouseLeave 不会向 dom 写入deactive 关闭 弹出框函数     onMouseEnter 时候 执行销毁其它弹出框时候就会 调用不到
改动方案：onMouseLeave 去除 isPrevMenuHiddening 校验
优化： 销毁弹框事件不挂在dom 上面  减少dom上面事件 节省内存
=> fix: 🐛 fast switch menubar-item lead to multiple popup

.github/workflows/ci.yml
fix secrets not accessable
fix #424
=> ci(fix): 👷 🐛 use pull_request_target event hook

examples/x6-example-features/src/pages/scroller/index.tsx, packages/x6/src/graph/format.ts
=> fix: 🐛 get completed picture when execue toPNG

packages/x6/src/graph/view.ts
windows下页面没有获取焦点的情况下，mousedown事件之后紧接着会出现一个mousemove事件,这个是chrome的bug
https://bugs.chromium.org/p/chromium/issues/detail?id=721341&q=trigger%20mousemove%20event%20on%20first%20click&can=1
可在 [F2etest](https://f2etest.alibaba-inc.com/browser)上选择chrome浏览器访问demo进行复现：  https://codepen.io/MSCAU/pen/mzOBpX.
=> fix: fix mousemove event fires on first mousedown

packages/x6/src/addon/scroller/index.ts, packages/x6/src/view/view.ts
* add clientSize cache `cacedClientSize` in scroller when resize to reduce reflow times
* add `setClass` method in view to enable set classList at onece to reduce reflow times
Enhance performance by reduce reflow times.
=> perf: ⚡️ add clientSize cache and setClass for reducing reflow

packages/x6-vue3-shape/README.md, packages/x6-vue3-shape/package.json, packages/x6-vue3-shape/rollup.config.js, packages/x6-vue3-shape/src/hook.ts, packages/x6-vue3-shape/src/index.ts, packages/x6-vue3-shape/src/node.ts, packages/x6-vue3-shape/src/registry.ts, packages/x6-vue3-shape/src/shims-vue.d.ts, packages/x6-vue3-shape/src/view.ts, packages/x6-vue3-shape/tsconfig.json, packages/x6-vue3-shape/tslint.json
Added X6-Vue3-Shape to support rendering Vue3 components
Added x6-vue3-shape code to enable X6 to render Vue3 components.
X6 currently does not support VUE3 components. Since the official version of Vue3 has been available for some time, some people may want to render Vue3 components with X6, so I developed this plugin using the React and Vue2.x related source code implementations.
- [x ] New feature (non-breaking change which adds functionality)
=> feat: ✨ add x6-vue3-shape

packages/x6/src/addon/dnd/index.ts, packages/x6/src/addon/minimap/index.ts, packages/x6/src/graph/css.ts
In current version, css style will be removed after every instance is disposed. this will break alive graph instances if there exists multiple x6 graph instances.
Import a single counter variable to ensure that css style is removed util  all instances are disposed.
=> fix: 🐛 make sure css resource is disposed  after all instance disposed

packages/x6/src/addon/selection/index.ts, packages/x6/src/model/cell.ts, packages/x6/src/model/node.ts
When node translate, its children make unnecessary translation by `onNodePositionChanged` in selection addon when selected. To avoid that, add flag to translation options to filter those translated nodes.
=> fix: 🐛 fix node translation with selected children

packages/x6/src/util/dom/text.ts
在 firefox 下计算 text 的 bbox 有误差，修改成直接计算 tspan 的 bbox
=> fix: 🐛 fix bbox calc error in firefox

packages/x6/src/addon/selection/index.ts
translateSelectionNodes 只有手动触发才会执行，解决代码触发某个选中节点平移时，造成的多个节点响应问题。
=> fix: 🐛 translateSelectionNodes is only triggered manually

packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/options.ts, packages/x6/src/model/cell.ts, packages/x6/src/model/node.ts
解决下面三个问题：
1. 开启 showSelectionBox 后，选中节点无法响应节点事件 https://github.com/antvis/X6/issues/1079 https://github.com/antvis/X6/issues/962  这里增加新的配置项：`pointerEvents`
2. 不开启 showSelectionBox，在群组中，移动节点，造成循环移动
3. 选中节点平移时，如果开启 restrict，要考虑所有选中节点是否超过限制
=> feat: ✨ optimize selection event handle

packages/x6-angular-shape/README.md, packages/x6-angular-shape/package.json, packages/x6-angular-shape/src/view.ts, packages/x6-angular-shape/tsconfig.json, sites/x6-sites/docs/tutorial/advanced/react.zh.md
close #1217 
Support pass arguments to the component or templateRef
=> feat: x6-angular-shape support pass arguments

packages/x6/src/addon/selection/index.ts
点击 selectionBox 的时候可以冒泡，以触发 document 上的事件。
=> fix: 🐛 not stopPropagation when mousedown

packages/x6/src/registry/tool/segments.ts, packages/x6/src/registry/tool/vertices.ts
edge 相关的 segment 和 vertices tool 需要有一个 onChanged 回调，来渲染 & 保存顶点数据
=> fix: segments & vertices tool add onChanged callback

examples/x6-example-features/src/pages/tools/contextmenu.tsx, examples/x6-example-features/src/pages/tools/tooltip.tsx, sites/x6-sites/examples/edge/tool/demo/context-menu.tsx, sites/x6-sites/examples/edge/tool/demo/meta.json
=> fix: 🐛 optimize contextmenu tools

packages/x6/src/addon/selection/index.ts
=> perf: ⚡️ improve box selection performance

packages/x6/src/graph/renderer.ts, packages/x6/src/model/model.ts
=> fix: 🐛 can not select flat edge

packages/x6/src/addon/selection/index.ts
1. 解决在 selecting 中 following 设置为 false 时，节点移动异常问题
=> fix: 🐛 stop propagation when enable following

packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/graph.ts, packages/x6/src/graph/selection.ts
https://github.com/antvis/X6/issues/1325#issuecomment-932722390
Ralated: #1325, #1393
添加 `batch: boolean` 选项，在选中时跳过 `select` `unselect` 流程，直接使用 `reset` 重置 `collection`。 See #1393
解决大量切换选中项目时的性能问题，see #1325
=> feat: ✨ add batch for selection

packages/x6/src/registry/router/manhattan/obstacle-map.ts, packages/x6/src/registry/router/manhattan/options.ts, sites/x6-sites/docs/api/registry/router.en.md, sites/x6-sites/docs/api/registry/router.zh.md
manhattan 路由中增加 excludeHiddenNodes 配置，是否计算隐藏节点位置
=> feat: ✨ add excludeHiddenNodes for manhattan router

configs/eslint-config/CHANGELOG.md, configs/package-json/CHANGELOG.md, configs/stylelint-config/CHANGELOG.md, examples/x6-app-dag/CHANGELOG.md, examples/x6-app-draw/CHANGELOG.md, examples/x6-app-er/CHANGELOG.md, examples/x6-example-features/CHANGELOG.md, examples/x6-example-features/src/pages/case/mind.less, examples/x6-example-features/src/pages/case/mind.tsx, packages/x6-vector/CHANGELOG.md, sites/x6-sites-demos-helper/CHANGELOG.md, sites/x6-sites-demos/CHANGELOG.md, sites/x6-sites/CHANGELOG.md, sites/x6-sites/examples/edge/tool/demo/context-menu.tsx, sites/x6-sites/examples/edge/tool/demo/meta.json, sites/x6-sites/examples/edge/tool/demo/tooltip.tsx, sites/x6-sites/examples/showcase/practices/demo/meta.json, sites/x6-svg-to-shape/CHANGELOG.md
=> docs: 📚️ update tooltip demo

packages/x6/src/registry/tool/vertices.ts
In the `vertices` tool, allow inserting points anywhere on the edge by changing the method used for vertex addition.
Currently the `vertices` EdgeTool does not allow inserting new points between exising points, only at the end of the edge.
Fix by using `insertVertex` instead of `setVertexAt` such that a new vertex is guaranteed to be added.
The current behavior is unnatural for end-users, because one would expect the tool to create a point wherever they click on the edge.
Fix #1679
=> fix: 🐛 unexpected user feedback in "vertices" edge tool

packages/x6/src/graph/keyboard.ts
=> fix: node input cannot get focus when keyboard options.global is enabled

sites/x6-sites/docs/tutorial/basic/node.zh.md
fix wrong url of quick-start from /zh/docs/tutorialgetting-started to /zh/docs/tutorial/getting-started
the right url is  /zh/docs/tutorial/getting-started, but unfortunately in this file, it was /zh/docs/tutorialgetting-started
=> docs: fix wrong url of quick-start

.gitignore, packages/x6-common/__tests__/dom/attr.test.ts, packages/x6-common/__tests__/dom/css.test.ts, packages/x6-common/__tests__/dom/prefix.test.ts, packages/x6-common/__tests__/dom/style.test.ts, packages/x6-common/src/dom/css.ts, packages/x6-common/src/dom/main.ts, packages/x6-common/src/dom/prefix.ts, packages/x6-common/src/types.ts, tsconfig.json
=> feat: ✨ add css method for dom

packages/x6/src/addon/scroller/index.ts
当画图面板resize时，scroller也会重新计算宽高。但是计算的宽高值不包含滚动条的宽度，导致计算的宽高值在多次resize反复下，变得越来越小
=> fix: 🐛 fix scroller resize size miscalculation when graph resize

packages/x6/src/style/raw.ts, packages/x6/src/util/dom/geom.ts
=> fix: fix animationOptions type

packages/x6-geometry/package.json, packages/x6-vector/package.json, packages/x6/package.json
删除 `x6` `x6-vector` `x6-geometry` 三个包 `package.json` 文件中的 browserslist 配置。
在 X6 的源码中，有尝试检测当前执行环境，是否原生支持 class 风格的判断代码。  
https://github.com/antvis/x6/blob/master/packages/x6/src/util/object/inherit.ts#L31  
```
class A {}
const isNativeClass =
/^\s*class\s+/.test(`${A}`) || /^\s*class\s*\{/.test(`${class {}}`)
```
在 @antv/x6@1.31.4 包中，其 es 目录中，这段代码是 class 风格的。  
/.../node_modules/@antv/x6/es/util/object/inherit.js  
```
class A {
}
const isNativeClass = /^\s*class\s+/.test(`${A}`) || /^\s*class\s*\{/.test(`${class {
}}`);
``` 
其 lib 目录中，这段代码是 function 风格的。  
/.../node_modules/@antv/x6/lib/util/object/inherit.js  
```
var A = /** @class */ (function () {
function A() {
}
return A;
}());
var isNativeClass = /^\s*class\s+/.test("" + A) || /^\s*class\s*\{/.test("" + /** @class */ (function () …
```
=> fix: remove the browserslist configuration in package.json

sites/x6-sites/docs/api/model/cell.zh.md
addTools函数被重载，第二个参数还可以是工具组的别称，但是文档里没有提及
在学习[边工具demo](https://x6.antv.vision/zh/examples/edge/tool#vertices)时，误以为`onhover`是另一个工具名称，查看api文档时发现工具组应该用数组包裹起来，于是认为可能是options，可是options应该是键值对而非字符串。查阅源码后发现第二个参数可以是这组添加的工具的别称，作为`hasTools(name)`的参数。
=> docs: update api description of addTools

packages/x6/src/view/edge.ts, packages/x6/src/view/tool.ts
don't apply renderExternalTools when edge update. Close https://github.com/antvis/X6/issues/2071
=> fix: 🐛 not rerender tools when edge update

packages/x6/src/addon/minimap/index.ts
In panning mode, minimap grpah not show the all shapes in content view, so listen cell:added cell:removed reseted events to zoom minimap graph to fit content.
=> fix: 🐛 auto zoom minimap graph to fit content

.github/workflows/pr-label-status-dummy.yml, .github/workflows/update-cache.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

packages/x6/src/view/node.ts
bug : validateMagnet 返回false，拖拽port可以移动node 
原因：
在点击port 的时候，如果validateMagnet  返回false 时 执行 node 上 onMouseDown方法，因为没有阻止冒泡，所以触发了节点上的startNodeDragging 方法
=> fix: 🐛 Fixed the bug that node moved when draging port #2216

packages/x6/src/util/array/array.ts, packages/x6/src/view/node.ts
pick the max zindex node when frontOnly enabled in embending
=> fix: 🐛 pick the max zindex node when frontOnly enabled in embending

packages/x6/src/registry/attr/connection.ts, sites/x6-sites/docs/api/registry/attr.en.md, sites/x6-sites/docs/api/registry/attr.zh.md
X6 目前为 <path> 提供了 connection 的一个属性，可通过此方法渲染path的两边。
https://x6.antv.vision/zh/docs/api/registry/attr#connection
但是我想渲染相反的地方，只渲染中间
```js
edge.attr('pathSelector', {
connection: { stubs: 40, reverse: true },
stroke: 'red',
fill: 'none',
})
```
=> feat: ✨ New property for edge connection attr

examples/x6-example-features/src/pages/undo/index.tsx, packages/x6/src/graph/history.ts, packages/x6/src/view/node.ts
Patches incorrect behaviors pertaining to undo/redo a "drag + embed" combo.
Closes #2421
Current version of `History` treats a "node dragging" interaction followed by an "embedding" interaction as three separate actions, meaning that it would take 3 undo's to fully revert the canvas to a previous state i.e. revert the moved node to its previous position — even though from the user's perspective, this really all happens in one dragging motion, **thus users would expect the dragging to be undone by invoking undo just once.**
To provide this expected behavior, this fix patches the `history` addon such that this specific interaction would be merged under the hood.
=> fix(history): 🐛 try to merge move+embed into 1 undo

packages/x6/src/util/scheduler/index.ts
=> fix: 🐛 #2581 修复 scheduler 任务调度的问题 (#2581)

packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-keyboard/src/keyboard.ts, scripts/build-dev
=> fix: 🐛 fix type error in keyboard plugin

packages/x6-react-shape/package.json, packages/x6-react-shape/src/view.ts
=> fix: support react 17

packages/x6/src/registry/tool/arrowhead.ts
https://github.com/antvis/X6/issues/3064
比如我想在箭头上这么定义,加上一个**fallbackAction: "remove"**,好让箭头在拖到空白的地方,能被移除掉,而不是象现在这样,自动还原
建议这么修改一下这里,以解决这个问题
[/packages/x6/src/registry/tool/arrowhead.ts#L54-L55](https://github.com/antvis/X6/blob/master/packages/x6/src/registry/tool/arrowhead.ts#L54-L55)
https://github.com/antvis/X6/blob/master/packages/x6/src/registry/tool/arrowhead.ts#L54-L55
```
cell.addTools([
{
name: "target-arrowhead",
args: {
fallbackAction: "remove",
},
},
]);
```
在箭头拖到空白的地方,能被移除掉,而不是象现在这样,自动还原
_No response_
- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
_No response_
=> fix: arrowhead not get options bug

packages/x6-common/src/dom/attr.ts
Add `textLength` and `lengthAdjust` attributes to CASE_SENSITIVE_ATTR
```js
const CASE_SENSITIVE_ATTR = [
'viewBox',
'attributeName',
'attributeType',
'repeatCount',
'textLength',
'lengthAdjust',
]
```
=> fix: add textLength & lengthAdjust to CASE_SENSITIVE_ATTR

tsconfig.json
fix Class constructor xx cannot be invoked without 'new'
Uncaught TypeError: Class constructor Mh cannot be invoked without 'new'
https://github.com/antvis/X6/issues/3270
=> fix: cannot be invoked without new

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
此 PR 修复了 v1 文档中存在的一个谬误：
`React.memo` 接受的第二个参数 `propsAreEqual `为 `true` 时，则认为数据没有发生改变，不会重新渲染，反之会重新渲染。
当节点的数据没有发生改变时，`next.node?.hasChanged('data')` 的结果为 `false`，应该取一次 `!` 而不是直接转为 Bool 值。
=> docs(v1-react): fix memo equal condition

sites/x6-sites/docs/tutorial/basic/events.zh.md
补充 view:mounted 和 view:unmounted 文档
补充 view:mounted 和 view:unmounted 文档
closes https://github.com/antvis/X6/issues/3374
新增了view:mounted和view:unmounted事件，文档同步更新
=> docs: 补充 view:mounted 和 view:unmounted 文档

sites/x6-sites/docs/tutorial/plugins/transform.zh.md
In the websites: "https://x6.antv.antgroup.com/tutorial/plugins/transform#api", sample code has careless mistake
```ts
new Transform({
resizing: {
enabled: true,
orthogonal(ndoe: Node) { //'ndoe' to 'node'
const { enableOrthogonal } = node.getData();
return enableOrthogonal;
},
},
});
```
=> careless mistake fix of docs

packages/x6/src/model/edge.ts
Added Edge rendering Check: execute newParent.embed() only when the parent node is different from prevParent node
Closes #3632
=> fix(Group): add Condition:Embeds the edge if source and target are not same

sites/x6-sites/docs/api/registry/port-layout.zh.md
The port-layout zh document has several typos in tables
- [x ] Docs (changes that only update documentation)
=> docs: fix port-layout zh doc typos

packages/x6/src/view/edge.ts
ref: https://github.com/antvis/X6/issues/3601
在修改 label position 之前检测 label node 是否存在
=> fix: check labelNode existed before change postion

packages/x6-vue-shape/src/teleport.ts, packages/x6-vue-shape/src/view.ts
This change does not affect the original usage, and provides a new way to getting nodes and graph.
This change does not affect the original usage, and provides a new way to getting nodes and graph.
参考 #3756，由于只提供provide的方式在webpack模块联邦打包后，存在问题，导致inject上下文获取不到，通过h渲染子组件时传入props的方式就能保证子组件能获取到对应方法。这个改动并不影响原有使用，相当于提供了一个新的方式。
=> feat: x6-vue-shape supports getting nodes and graph in the props 

sites/x6-sites/docs/api/registry/connector.zh.md
=> docs: wobble parameter names are incorrect

sites/x6-sites/docs/api/model/cell.zh.md
https://x6.antv.vision/zh/docs/api/model/cell/#setdata 中，出现了两次 { overwrite: true }，第二个应该是 { deep: true }。
当 options.overwrite 为 true 时，替换旧数据：
```
cell.setData(data, { overwrite: true })
```
当 options.deep 为 false 时，与原数据进行浅 merge：
```
cell.setData(data, { overwrite: true })
```
=> docs: cell.setData, `deep: false` code error

sites/x6-sites/docs/tutorial/intermediate/react.zh.md
Close https://github.com/antvis/X6/issues/3774
=> docs: add warn in react shape

packages/x6-common/src/dom/text.ts
=> feat: breakText method support line wrapping text

packages/x6/src/renderer/scheduler.ts, sites/x6-sites/docs/tutorial/basic/events.zh.md
Close https://github.com/antvis/X6/issues/3915
=> feat: add render:done event

sites/x6-sites/examples/edge/tool/demo/context-menu.tsx, sites/x6-sites/examples/edge/tool/demo/tooltip.tsx
Close https://github.com/antvis/X6/issues/3906
=> docs: optimize examples for tools

packages/x6-common/src/common/disposable.ts, packages/x6-plugin-minimap/src/index.ts, packages/x6/src/graph/graph.ts
Close https://github.com/antvis/X6/issues/3943
=> fix: optimize dispoese minimap

packages/x6-plugin-dnd/package.json, packages/x6-plugin-dnd/src/index.ts, pnpm-lock.yaml
=> fix: use `dom-align` to position dnd container (#3978)

sites/x6-sites/.dumirc.ts, sites/x6-sites/package.json
=> chore: update dumi-theme-antv

packages/x6-common/src/dom/matrix.ts, packages/x6-common/src/dom/prefix.ts, packages/x6-common/src/dom/selection.ts, packages/x6-common/src/dom/text.ts, packages/x6-common/src/polyfill/index.ts, packages/x6/src/util/index.ts
X6在多处module scope中直接访问了`document`、`window`等仅在client端可用的变量，导致一旦`import '@antv/X6'`服务端渲染就会出错（根据README，X6本应该支持服务端渲染）https://github.com/antvis/X6/blob/f2cae9637ebe1d3f1c26fe5209eae6e623e7c842/README.md?plain=1#L32
本PR将`document`等移至函数中，或加上条件保护，使代码在server端也能正常运行。
fix #4095
=> fix: avoid access document or window in server side

packages/x6/src/graph/view.ts, packages/x6/src/view/view.ts
修复内存泄漏问题
最初的pr #4009 
因为没有考虑到 Graph View 的 container 需要保留, 在 #4023 中注释掉了 view 的清理逻辑, 导致会重新引发内存泄漏
现给view添加了清理时保留 container 的选项, 以实现兼容 Graph View 的历史逻辑
=> fix: memory leak of graph view dispose(introduce by #4023)

packages/x6/src/graph/options.ts, packages/x6/src/view/edge.ts, sites/x6-sites/docs/api/model/interaction.zh.md
完成 https://github.com/antvis/X6/issues/3963，支持吸附到节点时基于bbox计算距离
Close https://github.com/antvis/X6/issues/3963
当吸附到边时，默认为基于最近距离计算，但是吸附到节点时默认为基于节点中心点计算距离且不支持配置。针对连接到母线这种情况吸附到中心点的体验比较差，因此新增了配置项 `snapNode` , 默认为 `center`, 可配置为 `bbox`, 默认值保留原来的行为，配置为 `bbox` 时基于包围框距离判断是否吸附。
- [ x] New feature (non-breaking change which adds functionality)
=> feat: allow calculate distance by bbox when snap to node

packages/x6/src/graph/options.ts, packages/x6/src/view/edge.ts
=> fix: destroy custom label before render

packages/x6-plugin-minimap/src/index.ts
bind minimap plugin to graph without scroller
=> fix: bind minimap plugin to graph without scroller

packages/x6-plugin-selection/src/selection.ts
see [#4062](https://github.com/antvis/X6/issues/4062)
see [#4062](https://github.com/antvis/X6/issues/4062)
=> feat: selection's pointerEvents support function type

packages/x6-plugin-export/src/index.ts
@antv/x6-plugin-export's options table show that the default-value of serializeImages and copyStyles is the true.However, the option argument has been set {} which will cause serializeImages or copyStyles is undefined in runtime. the logical truth code won't be executed.
=> fix(plugin:export): it should have default value 'true' through doc

packages/x6/src/graph/panning.ts, sites/x6-sites/docs/api/graph/panning.zh.md
在 panning modifiers 添加 space ，想只在 panning 中修改，所以想 isMatch 中的事件参数直接添加 spaceKey 直接进行判断了
=> feat: panning modifiers add space

packages/x6/src/view/edge.ts
edge的label渲染从labels中读取的配置，但是每次render的时候都会update 从attr的text中更新了每个label的属性，导致渲染错误，所以在update中将text单独取出去了
=> fix: edge rendering correct label attrs

packages/x6/src/registry/node-anchor/bbox.ts, packages/x6/src/registry/node-anchor/middle-side.ts, packages/x6/src/registry/node-anchor/orth.ts
=> fix: get wrong anchor when a node is invisible

sites/x6-sites/docs/api/model/cell.zh.md
=> fix: toJSON({ diff: true })没有达到预期效果 #4297

packages/x6/src/graph/mousewheel.ts, pnpm-lock.yaml
在 `mousewheel` 计算下一个缩放尺寸时，会因为js浮点数计算问题导致缩放尺寸计算存在误差：
- 即在缩小画布时，会计算出增大画布的缩放比例；
- 在放大画布时，会计算出缩小画布的缩放比例
在某些特定情况下，会导致画布的缩放比例被卡在某两个值之间来回切换，导致画布无法进行缩放。
#4168
=> fix: 浮点数精度丢失导致画布缩放卡死

packages/x6-react-shape/src/view.ts
x6 v1版本在开启 async mode后 自定义注册的react节点 有概率出现如下报错
v1需要对应 如下x6-react-shape v2 做空值校验
=> fix: react-shape this.selectors must valid

src/registry/tool/editor.ts
=> fix: edge editor text invalid when configuring the arrowhead

src/plugin/selection/selection.ts
fixed: https://github.com/antvis/X6/issues/3874
修改后效果图：
=> fix: extra offset may occur when reverse selecting in Selection plugin
