README.md, examples/x6-example-components/package.json, examples/x6-example-drawio/package.json, examples/x6-example-drawio/src/pages/editor.ts, examples/x6-example-features/package.json, examples/x6-example-features/src/pages/anchors.tsx, examples/x6-example-features/src/pages/flowchart/util.ts, examples/x6-example-features/src/pages/helloworld.tsx, packages/x6-components/package.json, packages/x6/README.md, packages/x6/package.json, packages/x6/src/core/cell.ts, packages/x6/src/core/model.ts, packages/x6/src/core/view.ts, packages/x6/src/graph/connection-manager.ts, packages/x6/src/graph/creation-accessor.ts, packages/x6/src/graph/creation-manager.ts, packages/x6/src/graph/group-manager.ts, packages/x6/src/graph/retrieval-accessor.ts, packages/x6/src/handler/connection/preview.ts, packages/x6/src/handler/edge/handler.ts, packages/x6/src/handler/node/preview.ts, packages/x6/src/route/er.ts, packages/x6/src/route/orth.ts, packages/x6/src/types.ts, packages/x6/src/version.ts
=> feat: data driven

examples/x6-example-components/package.json, examples/x6-example-drawio/package.json, examples/x6-example-features/package.json, examples/x6-example-features/src/pages/anchors.tsx, examples/x6-example-features/src/pages/group.tsx, examples/x6-example-features/src/pages/helloworld.tsx, examples/x6-example-features/src/pages/ports.tsx, examples/x6-example-features/src/pages/routers.tsx, examples/x6-example-features/src/pages/snapline.tsx, packages/x6/package.json, packages/x6/src/graph/creation-manager.ts, packages/x6/src/version.ts
=> should use id in json data as cell's id

examples/x6-example-features/src/pages/react-shape.tsx, packages/x6-react-shape/src/extend.ts, packages/x6/src/graph/common-accessor.ts, packages/x6/src/types/style.ts
1.  react节点: 能够通过component: (cell: Cell) => render(cell) 拿到最新react节点数据, 实现动态更新。
2. edge连线: 能够通过设置label: (cell: Cell)=>render(cell) 拿到最新的连线cell数据, 实现动态更新。
=> feat: dynamic update react node

examples/x6-example-drawio/package.json, examples/x6-example-features/package.json, packages/x6-react-shape/package.json, packages/x6/package.json, packages/x6/src/version.ts
=> chore: publish x6 0.2.7

README.md, examples/x6-example-drawio/package.json, examples/x6-example-features/package.json, examples/x6-example-features/src/layouts/index.tsx, examples/x6-example-features/src/pages/tojson-demo.tsx, packages/x6/package.json, packages/x6/src/core/cell.ts, packages/x6/src/core/model.ts, packages/x6/src/graph/creation-accessor.ts, packages/x6/src/graph/creation-manager.ts, packages/x6/src/version.ts
=> X6 to json

packages/x6/src/addon/scroller/index.ts, packages/x6/src/graph/format.ts, packages/x6/src/graph/graph.ts, packages/x6/src/graph/hook.ts, packages/x6/src/graph/print.less, packages/x6/src/graph/print.ts, packages/x6/src/index.less, packages/x6/src/util/datauri/index.ts, packages/x6/src/util/index.ts, packages/x6/src/util/unit/index.ts
=> feat: export graph to images & print preview

packages/x6/package.json, packages/x6/src/entity/events.ts
enent trigger时, 默认 return true, 不返回promise.resolve(true)
=> feat: event trigger默认返回true

packages/x6-site/package.json
https://github.com/antvis/gatsby-theme-antv/issues/186
=> fix: repository url in package.json

packages/x6/src/util/dom/elem.ts, packages/x6/src/util/dom/geom.ts
=> fix: fix getBBox function,now support get HTMLElement

packages/x6/jest.config.js
I need collect coverage information for all the files inside collectCoverageFrom directory，so i can find which methods are not being tested
As shown above, I can't see the details of the specific file
=> chore: modify coverage files for jest

.github/workflows/deploy-sites.yml
发 PR 时不部署，只有合并到 master 后才部署网站。
=> chore: Update deploy-sites.yml

.github/workflows/preview.yml
https://github.com/afc163/surge-preview
=> chore: add PR preview action

examples/x6-example-draw/.editorconfig, examples/x6-example-draw/.env, examples/x6-example-draw/.eslintrc, examples/x6-example-draw/.gitignore, examples/x6-example-draw/.umirc.ts, examples/x6-example-draw/package.json, examples/x6-example-draw/src/global.css, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigEdge/index.tsx, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigGrid/index.less, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigGrid/index.tsx, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigNode/index.tsx, examples/x6-example-draw/src/pages/components/ConfigPanel/index.tsx, examples/x6-example-draw/src/pages/components/FlowChart/index.less, examples/x6-example-draw/src/pages/components/FlowChart/index.tsx, examples/x6-example-draw/src/pages/components/Header/index.tsx, examples/x6-example-draw/src/pages/components/Sider/index.less, examples/x6-example-draw/src/pages/components/Sider/index.tsx, examples/x6-example-draw/src/pages/components/ToolBar/index.less, examples/x6-example-draw/src/pages/components/ToolBar/index.tsx, examples/x6-example-draw/src/pages/index.less, examples/x6-example-draw/src/pages/index.tsx, examples/x6-example-draw/src/reset.less, examples/x6-example-draw/src/x6Editor/constant.ts, examples/x6-example-draw/src/x6Editor/index.ts, examples/x6-example-draw/src/x6Editor/shape.ts, examples/x6-example-draw/tsconfig.json, examples/x6-example-draw/tslint.json, examples/x6-example-draw/typings.d.ts, yarn.lock
=> feat: add x6 draw demo

packages/x6/src/geometry/path/close.ts
兼容 ts4+
修复ts4报错
```
node_modules/@antv/x6/lib/geometry/path/close.d.ts(4,9):
4:9 'end' is defined as a property in class 'Segment', but is overridden here in 'Close' as an accessor.
2 | import { Segment } from './segment';
3 | export declare class Close extends Segment {
> 4 |     get end(): Point;
|         ^
5 |     get type(): string;
6 |     bbox(): any;
7 |     closestPoint(p: Point | Point.PointLike | Point.PointData): any;
```
我本来想把 Segment 的 end 属性定义改成 getter，但是看到其他 Segment 的子类都直接给 end 赋值了，简单起见就直接把 ts 的报错忽略掉
=> chore: support TypeScript 4

README.md
=> chore: fix david-dm link in README

examples/x6-example-draw/src/models/global.ts, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigEdge/index.tsx, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigGrid/index.tsx, examples/x6-example-draw/src/pages/components/ConfigPanel/ConfigNode/index.tsx, examples/x6-example-draw/src/pages/components/ConfigPanel/index.tsx, examples/x6-example-draw/src/pages/components/FlowChart/index.less, examples/x6-example-draw/src/pages/components/FlowChart/index.tsx, examples/x6-example-draw/src/pages/components/Header/index.less, examples/x6-example-draw/src/pages/components/Header/index.tsx, examples/x6-example-draw/src/pages/components/Sider/index.tsx, examples/x6-example-draw/src/pages/components/ToolBar/index.tsx, examples/x6-example-draw/src/x6Editor/flow-chart-shape.ts, examples/x6-example-draw/src/x6Editor/index.ts, examples/x6-example-draw/src/x6Editor/shape.ts
=> feat: ✨ complete flow chart

.github/workflows/mirror.yml
=> fix: wrong sync repo

packages/x6/src/graph/grid.ts
keep consistent with size and visible, sync modify type and args when draw grid
=> feat: ✨ sync modify options when draw grid

examples/x6-app-dag/package.json, examples/x6-app-draw/package.json, examples/x6-app-er/package.json, examples/x6-example-features/package.json, examples/x6-example-features/src/pages/ports/dynamic.tsx, examples/x6-example-sites-helper/package.json, examples/x6-example-sites/package.json, packages/x6-components/package.json, packages/x6-react-shape/package.json, packages/x6-react/package.json, packages/x6-sites/package.json, packages/x6/package.json, packages/x6/src/global/version.ts, packages/x6/src/model/model.ts
=> fix: issue-245

.github/workflows/config/needs-more-info.yml, .github/workflows/welcome.yml, examples/x6-app-dag/.umirc.ts, examples/x6-app-dag/package.json, examples/x6-app-draw/.umirc.ts, examples/x6-app-draw/package.json, examples/x6-app-er/.umirc.ts, examples/x6-app-er/package.json, examples/x6-example-features/package.json, packages/x6-react-components/package.json, packages/x6-react-shape/package.json, packages/x6-react/package.json, packages/x6/README.md, packages/x6/package.json, packages/x6/src/global/version.ts, packages/x6/src/graph/mousewheel.ts, packages/x6/src/util/platform/index.ts, sites/x6-sites-demos-helper/package.json, sites/x6-sites-demos/package.json, sites/x6-sites/package.json
=> Fix: mousewheel zoom is not natural

.github/workflows/config/auto-assign.yml, .github/workflows/config/label-commands.yml, .github/workflows/config/needs-more-info.yml, .github/workflows/lock.yml, .github/workflows/stale.yml, .github/workflows/welcome.yml, package.json, yarn.lock
=> refactor: ♻️ multiline comment message

sites/x6-sites/gatsby-config.js
=> chore: 🌐 add GATrackingId

sites/x6-sites/docs/api/graph.zh.md, sites/x6-sites/package.json, yarn.lock
1. add document for interacting
2. update gatsby-theme-antv verison to 1.0.1-beta11
3. Update website
=> docs: 📚️ update gatsby-theme-antv version

sites/x6-sites/site/pages/manual.less
=> fix: 🐛 method sign's bg and border color

examples/x6-example-features/src/pages/dnd/index.tsx, examples/x6-example-features/src/pages/embed/dnd.tsx, packages/x6/src/addon/dnd/index.ts, packages/x6/src/view/node.ts
fix highlight and 'node:change:parent' event not triggered
fix #271
=> fix: 🐛 dnd events

packages/x6/src/graph/options.ts, sites/x6-sites/docs/api/graph.zh.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md, sites/x6-sites/docs/tutorial/getting-started.zh.md
1. add doc of rotating、translating、resizing、transforming、embeding、highlighting、connecting
2. update website
=> docs: 📚️ supplementary document

examples/x6-example-features/src/pages/halo/index.tsx, examples/x6-example-features/src/pages/shape/standard.tsx, examples/x6-example-features/src/pages/transform/index.tsx, packages/x6/src/addon/halo/node-preset.ts, packages/x6/src/addon/transform/index.ts, packages/x6/src/addon/transform/util.ts, packages/x6/src/view/edge.ts, packages/x6/src/view/node.ts, sites/x6-sites/docs/tutorial/intermediate/events.zh.md
node:resize, node:resizing, node:resized, node:rotate, node:rotating, node:rotated
fix #275, re #273
=> feat: ✨ add some ui events

packages/x6/src/index.less
=> chore: test release

package.json, packages/x6/src/addon/halo/index.ts, packages/x6/src/addon/transform/index.ts, packages/x6/src/global/version.ts, yarn.lock
support two widgets: has-widget-transform, has-widget-halo
fix #279
=> feat: ✨ add xxx classname to node when widget visible

packages/x6/src/global/version.ts, packages/x6/src/graph/mousewheel.ts, sites/x6-sites/docs/api/graph.zh.md, yarn.lock
=> fix: mousewheel's guard option

examples/x6-example-features/src/pages/scroller/index.tsx, packages/x6/src/graph/mousewheel.ts
=> feat: ✨ add minScale and maxScale option for mousewheel

packages/x6/CHANGELOG.md
=> docs: remove invalid changelog

examples/x6-example-features/src/pages/embed/dnd.tsx, examples/x6-example-features/src/pages/embed/embedding.tsx, packages/x6/src/addon/dnd/index.ts, packages/x6/src/view/node.ts, sites/x6-sites-demos/packages/tutorial/basic/group/expand-shrink/src/app.css, sites/x6-sites-demos/packages/tutorial/basic/group/expand-shrink/src/app.tsx, sites/x6-sites-demos/packages/tutorial/basic/group/expand-shrink/src/settings.tsx
update the parent only when embedding finished
fix #295
=> refactor: ♻️ refactor embedding interaction

examples/x6-app-draw/src/pages/Graph/shape.ts
chagne shape attrs for draw demo
=> fix: 🐛 chagne shape attrs for draw demo

packages/x6/src/graph/renderer.ts
1. check edge's terminals before create edgeview 2. check edge's terminal when update edgeview
fix #300
=> fix: 🐛 should not render cell when invisible

.github/workflows/gitleaks.yml
https://github.com/ant-design/ant-design/blob/master/.github/workflows/gitleaks.yml
=> test: add gitleaks.yml

examples/x6-app-dag/src/layout/header/index.less, examples/x6-app-dag/src/layout/header/index.tsx, examples/x6-app-draw/src/global.css, examples/x6-app-draw/src/models/global.ts, examples/x6-app-draw/src/pages/Graph/index.ts, examples/x6-app-draw/src/pages/components/ConfigPanel/ConfigGrid/index.tsx, examples/x6-app-draw/src/pages/components/ConfigPanel/index.tsx, examples/x6-app-draw/src/pages/index.less, examples/x6-app-draw/src/pages/index.tsx, sites/x6-sites-demos/packages/api/graph/checkview/src/app.tsx, sites/x6-sites/site/locale.json, sites/x6-sites/site/pages/index.zh.tsx
1. 优化draw demo
2. 增加demo的源码链接
3. 更新demo中的intersectsWith方法
=> fix: optimize the draw the demo

examples/x6-example-features/src/pages/selection/index.tsx, packages/x6/src/addon/selection/index.ts, sites/x6-sites/docs/tutorial/basic/selection.zh.md
make filter function according with basic consciousness
fix #305
=> fix: 🐛 filter not working when select cell by calling `select()` api or by clicking cell

examples/x6-app-dag/src/layout/header/index.tsx, examples/x6-app-draw/src/pages/Graph/index.ts, examples/x6-app-draw/src/pages/index.tsx, examples/x6-app-er/src/pages/ERGraph/Toolbar/index.tsx, sites/x6-sites/package.json, sites/x6-sites/site/pages/index.zh.tsx, yarn.lock
=> fix: 🐛 add design for demos

examples/x6-app-draw/src/pages/index.tsx, sites/x6-sites/package.json, yarn.lock
=> fix: update gatsby-theme-antv version

examples/x6-example-features/src/pages/selection/index.tsx, packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/selection.ts, packages/x6/src/graph/view.ts, sites/x6-sites/docs/api/graph.en.md, sites/x6-sites/docs/api/graph.zh.md, sites/x6-sites/docs/tutorial/basic/mousewheel.en.md, sites/x6-sites/docs/tutorial/basic/mousewheel.zh.md, tslint.json
=> fix: node:xxx event was not triggered when interact with selection boxes

packages/x6-react-shape/package.json, packages/x6-react-shape/rollup.config.js, packages/x6/package.json, packages/x6/rollup.config.js, yarn.lock
replace `'process.env.NODE_ENV'`
fix #324
=> fix: 🐛 global `process` should be replaced when build with rollup

packages/x6/src/graph/mousewheel.ts
解决非scroller模式下滚轮滚动，graph的tranlate位置不正确问题
=> fix: 🐛 chang the call order of scale and translate

README.md, sites/x6-sites/docs/tutorial/getting-started.en.md, sites/x6-sites/docs/tutorial/getting-started.zh.md
=> docs: 📚️ add cdn instructions

examples/x6-example-features/src/pages/shape/index.html, packages/x6/src/util/platform/index.ts
fix by prefixed with window
fix #329
=> fix: 🐛 Uncaught ReferenceError: module is not defined

README.md, sites/x6-sites/docs/tutorial/getting-started.en.md, sites/x6-sites/docs/tutorial/getting-started.zh.md, sites/x6-sites/site/pages/index.less, sites/x6-sites/site/pages/index.zh.tsx
=> fix: 🐛 change readme to english

README.md, sites/x6-sites/site/pages/index.less, sites/x6-sites/site/pages/index.zh.tsx
1. change banner image
2. change readme image to HD
=> fix: change banner image in sites

examples/x6-app-draw/package.json, sites/x6-sites/examples/shape/edges/demo/edge.ts
=> fix: 🐛 add deps for x6-app-draw

examples/x6-example-features/src/pages/edge/edge-connected.tsx, packages/x6/src/view/edge.ts, sites/x6-sites/docs/tutorial/intermediate/events.en.md, sites/x6-sites/docs/tutorial/intermediate/events.zh.md
1. edge:connected事件中, previous... 参数在创建新的边的时候都是null
2. 修改文档，标记容易混淆的地方，在创建新的边的时候将previousCell认为是sourceCell
=> fix: optimize params for edge:connected event

packages/x6/src/addon/minimap/index.ts
=> fix: 🐛 not dispose graph in minmap

packages/x6/src/model/model.ts, sites/x6-sites-demos/packages/tutorial/basic/group/collapsable/src/app.tsx, sites/x6-sites-demos/packages/tutorial/basic/group/embedding/src/app.tsx, sites/x6-sites/examples/edge/label/demo/meta.json, sites/x6-sites/examples/edge/label/index.en.md, sites/x6-sites/examples/edge/label/index.zh.md, sites/x6-sites/examples/node/group/demo/collapsable.ts, sites/x6-sites/examples/node/group/demo/embedding-by-dnd.ts, sites/x6-sites/examples/node/group/demo/embedding-edges.ts, sites/x6-sites/examples/node/group/demo/embedding-nodes.ts, sites/x6-sites/examples/node/group/demo/expand-shrink.ts, sites/x6-sites/examples/node/group/demo/meta.json, sites/x6-sites/examples/node/group/demo/restrict-movement.ts
修复：添加边到画布后，将边链接的节点的共同父节点作为边的父节点。
添加：群组使用 DEMO
=> doc: group demo

packages/x6/src/graph/css.ts, packages/x6/src/graph/view.ts, packages/x6/src/util/dom/elem.ts
=> fix: issue 348

examples/x6-example-features/src/pages/graph/zoom.tsx, packages/x6/src/addon/scroller/index.ts, packages/x6/src/graph/graph.ts, packages/x6/src/graph/transform.ts, sites/x6-sites/docs/api/graph.en.md, sites/x6-sites/docs/api/graph.zh.md
1. 在普通画布上兼容scroller画布上的方法
2. 补充demo与文档
=> feat: compatible with scroller method in normal graph

examples/x6-example-features/src/pages/edge/custom-connector.tsx, examples/x6-example-features/src/pages/edge/custom-router.tsx, examples/x6-example-features/src/pages/edge/index.tsx, examples/x6-example-features/src/pages/embed/dnd.less, examples/x6-example-features/src/pages/embed/dnd.tsx, packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/selection.ts
- 修复：点击 selectionBox 不能取消选中；
- 修复：当不显示 selectionBox 时不能通过点击节点取消选中。
=> fix: issue 364

packages/x6/src/util/polyfill/index.ts, sites/x6-sites/docs/tutorial/basic/selection.en.md, sites/x6-sites/docs/tutorial/basic/selection.zh.md, sites/x6-sites/docs/tutorial/faq/epilog.en.md, sites/x6-sites/docs/tutorial/faq/epilog.zh.md
1. 增加 faq 的目录
2. selection 文档中增加 showNodeSelectionBox 和 showEdgeSelectionBox 说明 [#357](https://github.com/antvis/X6/issues/357)
3. 增加兼容代码
=> optimize faq doc

examples/x6-app-dag/src/pages/common/graph-common/shape/edge.ts, examples/x6-app-dag/src/pages/dag-canvas/canvas-toolbar.tsx, examples/x6-app-dag/src/pages/rx-models/experiment-graph.tsx
close:  #353
#353
- [] All new and existing tests passed.
=> fix(hisotry): fix history undo error

examples/x6-app-draw/src/models/global.ts, examples/x6-app-draw/src/pages/Graph/index.ts, sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md, sites/x6-sites/docs/tutorial/basic/cell.en.md, sites/x6-sites/docs/tutorial/basic/cell.zh.md, sites/x6-sites/docs/tutorial/log.en.md, sites/x6-sites/docs/tutorial/log.zh.md
1. 修复x6-app-draw 节点编辑文本不同步问题
2. 增加更新日志，后续有导致版本升级代码合并，需要在 log 中用清晰的文本描述更新内容
=> docs: add update log

sites/x6-sites/docs/tutorial/intermediate/events.en.md, sites/x6-sites/docs/tutorial/intermediate/events.zh.md
=> 修复文档错误_事件系统

examples/x6-app-dag/src/pages/rx-models/experiment-graph.tsx, examples/x6-example-features/src/pages/graph/zoom.tsx, examples/x6-example-features/src/pages/transitions/model.ts, packages/x6/src/shape/standard/image.ts
解决 width 和 height 配置在 image 节点中不生效
=> fix: fix size invalid on image node

packages/x6/src/types/modifier.ts
在修改官网 scroller 上demo错误问题时，会写出这样的代码：
```ts
onSettingChanged = (options: State) => {
let modifiers = options.modifiers
if (Array.isArray(modifiers) && modifiers.length === 0) {
modifiers = null
}
this.graph.setRubberbandModifiers(modifiers)
}
```
优化一下isMatch，引导用户写出更优雅的代码
=> fix: optimize the ModifierKey isMatch method

sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/about.zh.md
=> docs: http => https

scripts/monorepo-semantic-release/package.json, scripts/monorepo-semantic-release/src/plugin.ts, scripts/monorepo-semantic-release/yarn.lock
sync package to cnpm when published
fix #410
=> feat: ✨ auto sync with cnpm

examples/x6-app-draw/src/pages/Graph/index.ts, sites/x6-sites-demos/packages/tutorial/getting-started/transform/src/app.tsx, sites/x6-sites/docs/tutorial/basic/group.en.md, sites/x6-sites/docs/tutorial/basic/group.zh.md
1. 解决文档中几处错误
2. 解决draw demo中group无法被删除问题
=> fix group could not be deleted

packages/x6-vue-shape/README.md, packages/x6-vue-shape/package.json, packages/x6-vue-shape/rollup.config.js, packages/x6-vue-shape/src/hook.ts, packages/x6-vue-shape/src/index.ts, packages/x6-vue-shape/src/node.ts, packages/x6-vue-shape/src/registry.ts, packages/x6-vue-shape/src/shims-tsx.d.ts, packages/x6-vue-shape/src/shims-vue.d.ts, packages/x6-vue-shape/src/view.ts, packages/x6-vue-shape/tsconfig.json, packages/x6-vue-shape/tslint.json
增加 x6-vue-shape, x6 节点中支持 vue 组件的渲染，待补充官网文档
=> feat: add x6-vue-shape

README.md, examples/x6-app-draw/src/global.css, examples/x6-app-draw/src/pages/Graph/index.ts, examples/x6-app-draw/src/pages/Graph/shape.ts, sites/x6-sites/docs/api/registry/router.en.md, sites/x6-sites/docs/api/registry/router.zh.md, sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/about.zh.md, sites/x6-sites/docs/tutorial/contact.en.md, sites/x6-sites/docs/tutorial/contact.zh.md, sites/x6-sites/docs/tutorial/log.en.md, sites/x6-sites/docs/tutorial/log.zh.md
=> optimize the document

examples/x6-app-er/src/pages/ERGraphDemo/index.tsx
chore: function name typo in ER example code.
=> chore: function name typo in ER example code.

packages/x6-vue-shape/src/registry.ts, packages/x6-vue-shape/src/view.ts, sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> docs: 📚️ add x6-vue-shape docs

packages/x6/src/addon/stencil/index.ts, sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
=> docs: 📚️ add search docs for stencil

sites/x6-sites/docs/tutorial/basic/history.zh.md
=> enable错了 改成enabled

packages/x6/src/graph/hook.ts, packages/x6/src/view/cell.ts, sites/x6-sites/docs/api/graph/interaction.zh.md
1. 修改 html 为 dom对象是 判断bug
2. interacting 每一项支持函数
=> support function on interacting items

packages/x6-react-components/package.json, packages/x6-react-components/rollup.config.js, sites/x6-sites/docs/tutorial/advanced/components.en.md, sites/x6-sites/docs/tutorial/advanced/components.zh.md
支持 x6-react-components umd build
=> fix x6-react-components umd build

sites/x6-sites-demos/packages/tutorial/basic/scroller/playground/src/settings.tsx, sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md, sites/x6-sites/docs/tutorial/getting-started.en.md, sites/x6-sites/docs/tutorial/getting-started.zh.md
=> docs: 📚️ fix doc error

README.md, packages/x6/src/global/config.ts
=> fix: 🐛 remove code tracing

sites/x6-sites/docs/tutorial/advanced/layout.zh.md
npm install @antv/layout--save =》 npm install @antv/layout --save
=> npm install @antv/layout--save 增加空格，不然会提示找不到这个package

sites/x6-sites/docs/tutorial/advanced/layout.zh.md
gridLayout.fromJSON(newModel)  => graph.fromJSON(newModel)
=> gridLayout.fromJSON(newModel) 笔误

sites/x6-sites/docs/tutorial/log.en.md, sites/x6-sites/docs/tutorial/log.zh.md
=> docs: 📚️ update log

sites/x6-sites/docs/api/model/node.en.md, sites/x6-sites/docs/api/model/node.zh.md, sites/x6-sites/docs/tutorial/basic/port.en.md, sites/x6-sites/docs/tutorial/basic/port.zh.md
=> PortMetadata 类名错误，文档中显示为PortmMetadata，改正为PortMetadata

examples/x6-app-draw/src/pages/Graph/index.ts, packages/x6-react-shape/src/registry.ts, packages/x6-vue-shape/src/registry.ts, packages/x6-vue-shape/src/view.ts
1. 给 reactshape 和 vueshape 增加反注册方法
2. vueshape 中间的 div width和height设置为 100%
=> fix: 🐛 add unregister for react/vue shape

sites/x6-sites/examples/node/tool/demo/contextmenu.tsx, sites/x6-sites/examples/node/tool/demo/meta.json
=> docs: 📚️ add contextmenu demo

packages/x6/src/addon/transform/index.ts
1. mousemove 后再触发 node:resize 和 node:rotate 事件
2. 旋转角度不变时不触发 node:rotating 事件
=> fix: change node:resize and node:rotate event trigger times

packages/x6/src/addon/selection/index.ts
cell:changed 之后再更新selection box
=> fix: update selection box when cell:changed

sites/x6-sites/examples/showcase/practices/demo/tree.ts
=> docs: change graph sorting config

packages/x6-vue-shape/src/hook.ts
解决 vue-shape toJSON 和 fromJSON 时报错问题
=> fix: fix error in vue shape when formJSON

sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md
=> docs: fix doc error

sites/x6-sites-demos-helper/loaders/repo.js
=> docs: fix github link for demo

packages/x6/src/shape/standard/edge-doubled.ts, packages/x6/src/shape/standard/edge-shadow.ts, packages/x6/src/style/raw.ts, packages/x6/src/view/node.ts, sites/x6-sites/docs/tutorial/log.en.md, sites/x6-sites/docs/tutorial/log.zh.md
1. node 在不可移动下使用默认手型
2. double-edge 和 shadow-edge 模型手型为 pointer
3. 更新日志
=> fix: fix cursor error

sites/x6-sites/docs/tutorial/basic/history.en.md, sites/x6-sites/docs/tutorial/basic/history.zh.md
=> docs: change enable to enabled in history doc

examples/x6-app-draw/src/pages/Graph/data.ts, examples/x6-app-draw/src/pages/Graph/index.ts, sites/x6-sites-demos/packages/tutorial/basic/keyboard/playground/src/app.tsx
=> fix: port can connect multiple lines

packages/x6/src/addon/scroller/index.ts, sites/x6-sites/examples/edge/tool/demo/context-menu.tsx
解决 context-menu 上 menu-item 无法触发点击事件问题
=> docs: fix click event not fire in context-menu

sites/x6-sites/examples/interaction/edge/demo/create.tsx, sites/x6-sites/examples/interaction/edge/demo/meta.json
=> docs: add demo

examples/x6-app-draw/src/pages/Graph/index.ts
=> 修复draw示例中未对复杂节点的右击事件进行额外判断导致的错误

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md, sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md, sites/x6-sites/docs/tutorial/basic/port.en.md, sites/x6-sites/docs/tutorial/basic/port.zh.md, sites/x6-sites/docs/tutorial/faq/epilog.en.md, sites/x6-sites/docs/tutorial/faq/epilog.zh.md
1. 增加导出图片相关文档
2. 增加 registerVueComponet 说明
3. 增加用 react 渲染 port 访问入口
=> doc: rich document

sites/x6-sites/docs/tutorial/advanced/layout.en.md, sites/x6-sites/docs/tutorial/advanced/layout.zh.md
=> docs: add cdn for layout

examples/x6-app-draw/src/pages/Graph/data.ts, packages/x6/src/graph/print.ts, packages/x6/src/util/index.ts, packages/x6/src/util/string/html.ts
fix x6 error in meteor framework
=> fix: change $ to JQuery

packages/x6/src/model/cell.ts, sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md
add `removeTool` and `hasTool` method
fix #552
=> fix: 🐛 remove single tool by name or index

packages/x6/src/view/node.ts
auto update cursor style by movable status
fix #558
=> fix: 🐛 auto fix node's css className on mouseenter

README.en-us.md, packages/x6/src/shape/standard/path.ts, sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md, sites/x6-sites/docs/tutorial/faq/epilog.en.md, sites/x6-sites/docs/tutorial/faq/epilog.zh.md
1. 中文 README
2. 解决 path 节点 label 不显示问题
2. dispose 方法文档
3. 增加常见问题
=> docs: change readme language

packages/x6/src/addon/scroller/index.ts, packages/x6/src/graph/graph.ts, packages/x6/src/graph/size.ts
add `resizePage` method
fix #564
=> fix: 🐛 update page size as needed when graph size changed

packages/x6/src/addon/scroller/index.ts
=> fix: fix canot get graph

packages/x6/src/addon/stencil/index.less, packages/x6/src/addon/stencil/index.ts, packages/x6/src/style/raw.ts, sites/x6-sites-demos/packages/tutorial/basic/dnd/stencil/src/app.tsx, sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
=> fix: add `placeholder` and `notFoundText` for stencil component

packages/x6/src/graph/hook.ts
get registry first in html component
=> fix: get registry first in html component

packages/x6/src/graph/view.ts, packages/x6/src/registry/tool/vertices.ts, packages/x6/src/view/edge.ts, sites/x6-sites/examples/showcase/faq/demo/change-mode.tsx, sites/x6-sites/examples/showcase/faq/demo/meta.json
1. 解决 label 不能移动问题
2. 解决 vertexAddable 不生效问题
3. 增加切换交互模式的 dmeo
=> docs: add demo for interacting

README.md, sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md, sites/x6-sites/docs/tutorial/log.en.md, sites/x6-sites/docs/tutorial/log.zh.md
=> docs: update log

packages/x6/src/graph/hook.ts, packages/x6/src/shape/standard/html.ts, packages/x6/src/util/object/inherit.ts
=> fix: 🐛 support register html render object

packages/x6/src/view/node.ts
exclude edge on node:move event
=> fix: 🐛 exclude edge on node:move event

sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md, sites/x6-sites/docs/tutorial/intermediate/events.en.md, sites/x6-sites/docs/tutorial/intermediate/events.zh.md
=> docs: 📚️ add explain for mousemove event

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> docs: add registerVueComponent demo

examples/x6-example-features/src/pages/edge/custom-connector.tsx, sites/x6-sites/examples/edge/connector/demo/wobble.ts
=> fix: fix path error in custom router demo

examples/x6-example-features/src/pages/tools/contextmenu.tsx, sites/x6-sites/examples/edge/tool/demo/context-menu.tsx
=> fix: fix contextmenu show multiple times

packages/x6/src/view/node.ts, sites/x6-sites/docs/tutorial/basic/selection.en.md, sites/x6-sites/docs/tutorial/basic/selection.zh.md
fix trigger multiple moved event when close movable config
=> fix: fix trigger multiple moved event when close movable config

examples/x6-example-features/src/pages/edge/validate-connection.tsx, sites/x6-sites/examples/showcase/faq/demo/meta.json, sites/x6-sites/examples/showcase/faq/demo/validate-connection.ts
=> docs: add validate magnet demo

sites/x6-sites/examples/data/algorithm-category.json, sites/x6-sites/examples/layout/general/demo/circle.ts, sites/x6-sites/examples/layout/general/demo/dagre.ts, sites/x6-sites/examples/layout/general/demo/ellipse.ts, sites/x6-sites/examples/layout/general/demo/grid.ts, sites/x6-sites/examples/layout/general/demo/meta.json, sites/x6-sites/examples/layout/general/index.en.md, sites/x6-sites/examples/layout/general/index.zh.md, sites/x6-sites/examples/layout/tree/demo/meta.json, sites/x6-sites/examples/layout/tree/demo/mindmap.ts, sites/x6-sites/examples/layout/tree/index.en.md, sites/x6-sites/examples/layout/tree/index.zh.md, sites/x6-sites/gatsby-browser.js, sites/x6-sites/gatsby-config.js, sites/x6-sites/package.json
=> docs: add layout demo

packages/x6-vue-components/package.json, packages/x6-vue-components/src/index.ts, packages/x6-vue-components/src/split-box/box.vue, packages/x6-vue-components/src/split-box/index.ts, packages/x6-vue-components/src/split-box/resizer.vue, packages/x6-vue-components/src/split-box/splitbox.ts, packages/x6-vue-components/src/split-box/splitbox.vue, packages/x6-vue-components/src/split-box/style/index.less, packages/x6-vue-components/src/split-box/style/index.ts, packages/x6-vue-components/src/util/index.ts
feat: ✨ add splitbox vue component
=> feat: ✨ add splitbox vue component

sites/x6-sites/examples/showcase/faq/demo/meta.json, sites/x6-sites/examples/showcase/faq/demo/text-wrap.ts
=> docs: add text-wrap demo

examples/x6-example-features/src/pages/selection/custom-style.tsx, sites/x6-sites/examples/interaction/edge/demo/meta.json, sites/x6-sites/examples/interaction/edge/demo/selection.ts, sites/x6-sites/examples/interaction/edge/index.en.md, sites/x6-sites/examples/interaction/edge/index.zh.md
=> docs: add custom selection style demo

sites/x6-sites/examples/interaction/edge/demo/create.tsx
=> fix: fix can not create node when mouseup in demo

packages/x6/src/addon/scroller/index.ts, packages/x6/src/shape/standard/cylinder.ts, packages/x6/src/util/dom/text.ts, tslint.json
1. delete console.log
2. add no-console config
=> fix: delete console.log, add no-console config

sites/x6-sites-demos/packages/tutorial/advanced/animation/football/src/reg.ts, sites/x6-sites-demos/packages/tutorial/advanced/animation/yellow-ball/src/app.tsx, sites/x6-sites-demos/packages/tutorial/basic/selection/playground/src/app.tsx, sites/x6-sites-demos/packages/tutorial/basic/snapline/playground/src/app.tsx
=> fix: fix demo error in sites

packages/x6/src/view/node.ts
=> fix: fix move event trigger error

examples/x6-app-draw/src/pages/Graph/index.ts, examples/x6-app-draw/src/pages/Graph/shape.ts
- 官方示例中，点击/拖动node的label会出现编辑框。
- 这段代码会导致序列化/反序列化之后，node的label不显示。
```js
cell.attr('text/style/display', 'none')
```
=> fix: editableNode bugs of x6-app-draw

examples/x6-app-draw/src/pages/Graph/data.ts, examples/x6-app-draw/src/pages/Graph/index.ts, examples/x6-app-draw/src/pages/Graph/shape.ts, examples/x6-app-draw/src/pages/index.tsx
=> fix: fix text not wrap error

examples/x6-example-features/src/pages/performance/report/normal/edge.json, examples/x6-example-features/src/pages/performance/report/normal/edge.tsx, examples/x6-example-features/src/pages/performance/report/normal/node.json, examples/x6-example-features/src/pages/performance/report/normal/node.tsx, examples/x6-example-features/src/pages/performance/report/normal/port.json, examples/x6-example-features/src/pages/performance/report/normal/port.tsx, examples/x6-example-features/src/pages/performance/report/react/node.json, examples/x6-example-features/src/pages/performance/report/react/node.tsx, examples/x6-example-features/src/pages/performance/report/react/port.json, examples/x6-example-features/src/pages/performance/report/react/port.tsx, sites/x6-sites/docs/tutorial/performance.en.md, sites/x6-sites/docs/tutorial/performance.zh.md
=> docs: add perforamce report

examples/x6-example-features/src/pages/performance/report/normal/edge.tsx, examples/x6-example-features/src/pages/performance/report/normal/node.tsx, examples/x6-example-features/src/pages/performance/report/normal/port.tsx, examples/x6-example-features/src/pages/performance/report/react/node.tsx, examples/x6-example-features/src/pages/performance/report/react/port.tsx, sites/x6-sites/docs/tutorial/getting-started.en.md, sites/x6-sites/docs/tutorial/getting-started.zh.md
=> fix: fix demo import path error

packages/x6-react-shape/src/hook.ts, packages/x6-vue-shape/src/hook.ts
=> fix: fix type error

packages/x6/src/index.less
=> fix: change css selector foreignobject to foreignObject

sites/x6-sites/examples/node/tool/demo/editable.ts
=> fix: fix editable cell demo

packages/x6/src/geometry/rectangle.ts, packages/x6/src/registry/router/er.ts
=> fix: fix spelling error

packages/x6/src/graph/keyboard.ts
设置 global:true 时 e.target 是 body
=> fix: fix keyboard event not trigger

packages/x6/src/addon/selection/index.ts, sites/x6-sites/docs/tutorial/basic/selection.en.md, sites/x6-sites/docs/tutorial/basic/selection.zh.md
selection 中增加 following 配置，解决多选节点拖动时卡顿问题。
https://gw.alipayobjects.com/mdn/rms_43231b/afts/img/A*nt5KQqqZHDUAAAAAAAAAAAAAARQnAQ
=> feat: add following config for selection

packages/x6/package.json
=> docs: add browserslist

examples/x6-app-draw/src/pages/Graph/index.ts
=> docs: set node front when embeded

sites/x6-sites/examples/showcase/faq/demo/change-mode.tsx
add demo for config  interacting for one node
=> docs: add demo for config  interacting for one node

packages/x6/src/util/polyfill/index.ts
解决一些场景下this.addEventListener为空导致报错问题
=> fix: add judgment in sepcial event

.husky/pre-commit, package.json
=> fix: 🐛 fix lerna not found error

package.json
=> fix: 🐛 change commit lint rule

package.json
add footer-max-line-length rule for commitlint
=> fix: add footer-max-line-length rule for commitlint

packages/x6/src/graph/mousewheel.ts
fix start pos error in mousewheel
=> fix: 🐛 fix start pos error in mousewheel

packages/x6/src/graph/size.ts
get container size use offsetxxx
=> fix: 🐛 get container size use offsetxxx

sites/x6-sites/docs/api/graph/transform.zh.md, sites/x6-sites/docs/tutorial/basic/mousewheel.en.md, sites/x6-sites/docs/tutorial/basic/mousewheel.zh.md
=> docs: 📚️ add minScale and maxScale config for mousewheel

sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md
fix typos in the docs.
change `garah` to `graph` .
=> docs: fix typos

sites/x6-sites/docs/api/graph/background.en.md, sites/x6-sites/docs/api/graph/clipboard.en.md, sites/x6-sites/docs/api/graph/coordinate.en.md, sites/x6-sites/docs/api/graph/graph.en.md, sites/x6-sites/docs/api/graph/grid.en.md, sites/x6-sites/docs/api/graph/history.en.md, sites/x6-sites/docs/api/graph/interaction.en.md, sites/x6-sites/docs/api/graph/keyboard.en.md, sites/x6-sites/docs/api/graph/minimap.en.md, sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/mousewheel.en.md, sites/x6-sites/docs/api/graph/other.en.md, sites/x6-sites/docs/api/graph/scroller.en.md, sites/x6-sites/docs/api/graph/selecting.en.md, sites/x6-sites/docs/api/graph/snapline.en.md, sites/x6-sites/docs/api/graph/transform.en.md, sites/x6-sites/docs/api/graph/view.en.md
=> docs: 📚️ add en docs

packages/x6-vue-shape/src/node.ts
=> fix: 🐛 add primer for vue-shape

packages/x6/src/addon/dnd/index.ts, sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
add containerParent config for dnd
=> feat: ✨ add containerParent config for dnd

packages/x6/src/addon/transform/index.ts, packages/x6/src/graph/hook.ts, packages/x6/src/graph/options.ts
add allowReverse option for resizing
=> feat: ✨ add allowReverse option for resizing

sites/x6-sites/examples/layout/general/demo/force.ts, sites/x6-sites/examples/layout/general/demo/meta.json
=> docs: 📚️ add force layout

packages/x6/src/addon/scroller/index.ts, packages/x6/src/graph/scroller.ts, sites/x6-sites/docs/api/graph/scroller.en.md, sites/x6-sites/docs/api/graph/scroller.zh.md
Allow disable auto resize by graph.scroller api which can give better performance, developer can call update api to update the scroller by manual
* Enable Auto Resize:
* Disable Auto Resize:
=> feat: ✨  allow disable auto resize in some high performance scenario

packages/x6/src/model/model.ts
=> fix: 🐛 add ToJSONData type

packages/x6/src/model/cell.ts
fix not refresh after removeTool
=> fix: 🐛 fix not refresh after removeTool

examples/x6-example-features/src/pages/tools/contextmenu.tsx, packages/x6/src/model/cell.ts, sites/x6-sites/examples/edge/tool/demo/context-menu.tsx
=> fix: 🐛 fix add tools not work

examples/x6-app-dag/src/pages/rx-models/graph-core.ts
=> fix: 🐛 disable panning before rubberband

sites/x6-sites-demos/packages/tutorial/advanced/layout/circular/package.json, sites/x6-sites-demos/packages/tutorial/advanced/layout/dagre/package.json, sites/x6-sites-demos/packages/tutorial/advanced/layout/grid/package.json
=> docs: 📚️ change layout version

sites/x6-sites-demos-helper/src/toolbar/index.tsx
=> fix: 🐛 temporarily disable stackblitz

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> docs: 📚️ fix vue2 docs

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> docs: 📚️ fix docs

examples/x6-example-features/src/pages/expand/tree/index.tsx, packages/x6/src/addon/minimap/index.ts
set the async of minimapGraph to be the same as sourceGraph
=> fix: 🐛 set the async of minimapGraph to be the same as sourceGraph

packages/x6/src/model/cell.ts
=> fix: 🐛 restrict unembed condition

examples/x6-example-features/src/pages/connector/er-rounded.tsx, packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/graph.ts, packages/x6/src/model/collection.ts
1. 解决 model 上的 sorted、updated、reseted 触发两次问题
2. 解决重复 sort 问题
=> fix: 🐛 fix model event trigger twice

packages/x6/src/util/dom/matrix.ts
=> feat: ✨ revert a lint fix commit

yarn.lock
=> fix: 🐛 fix websites error

.github/workflows/cache.yaml, .github/workflows/ci.yml, .github/workflows/deploy-sites.yml, .github/workflows/release.yml, configs/karma-config.js, configs/package-json/package.json, packages/x6-geometry/package.json, packages/x6-vector/package.json, packages/x6-vector/src/global/global.test.ts, packages/x6-vector/src/global/global.ts, packages/x6-vector/src/global/index.ts, packages/x6-vector/src/struct/point.test.ts, packages/x6-vector/src/struct/point.ts, packages/x6-vector/src/struct/svg-array.test.ts, packages/x6-vector/src/struct/svg-array.ts, packages/x6-vector/src/struct/svg-number.test.ts, packages/x6-vector/src/struct/svg-number.ts, yarn.lock
=> chore: 🛠️ make packages public

packages/x6-react-components/src/dropdown/index.tsx
release x6-react-components 1.1.3
=> fix: 🐛 release x6-react-components 1.1.3

.github/workflows/authors.yml, .github/workflows/auto-close-fixed-issues.yml, .github/workflows/auto-comment.yml, .github/workflows/contributors.yml, .github/workflows/create-issue-branch.yml, .github/workflows/delete-stale-releases.yml, .github/workflows/deploy-sites.yml, .github/workflows/issue-label-assignee.yml, .github/workflows/label-commands.yml, .github/workflows/lock.yml, .github/workflows/mirror.yml, .github/workflows/needs-more-info.yml, .github/workflows/pr-label-branch-name.yml, .github/workflows/pr-label-file-paths.yml, .github/workflows/pr-label-patch-size.yml, .github/workflows/rebase.yml, .github/workflows/release.yml, .github/workflows/slash-commands.yml, .github/workflows/stale.yml, .github/workflows/sync-labels.yml, .github/workflows/welcome.yml, README.md, packages/x6-geometry/README.md, packages/x6-vector/README.md, packages/x6-vector/package.json
- update build status base on ci action status
- update code coverage from codecov
=> [wip] chore: config badges in readme

examples/x6-app-draw/src/pages/components/ToolBar/index.tsx
x6-app-draw支持windows下ctrl组合快捷键
=> x6-app-draw支持windows下ctrl组合快捷键

sites/x6-sites/docs/tutorial/intermediate/events.en.md, sites/x6-sites/docs/tutorial/intermediate/events.zh.md
=> docs: 📚️ add embed event

sites/x6-sites/docs/api/ui/menu.en.md, sites/x6-sites/docs/api/ui/menu.zh.md
add name specification for menuitem
=> docs: 📚️ add name specification for menuitem

packages/x6-react-components/rollup.config.js, packages/x6-react/rollup.config.js
fix x6-react-components rollup config
=> fix: 🐛 fix x6-react-components rollup config

sites/x6-sites/examples/showcase/practices/demo/algo-flow.tsx
解决人工智能建模流程 demo 在 safari 下边的位置异常问题。
=> docs: 📚️ fix edge pos error in algo-flow demo

packages/x6/src/graph/mousewheel.ts
修复缩放因子计算法方式，缩放范围完全由 minScale 和 maxScale 决定
=> fix: 🐛 fix factor calculation in mousewheel

examples/x6-example-features/src/pages/shape/flowchart/shapes/card.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/data.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/document.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/internal-storage.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/manual-input.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/manual-operation.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/merge-or-storage.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/multi-document.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/off-page-reference.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/or.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/paper-tape.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/predefined-process.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/preparation.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/process.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/sequential-data.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/sort.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/stored-data.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/terminator.ts, examples/x6-example-features/src/pages/shape/flowchart/shapes/transfer.ts
=> fix: 🐛 fix type error

sites/x6-sites-demos-helper/loaders/repo.js, sites/x6-sites-demos/packages/api/graph/auto-resize/package.json
1. 解决 codesanbox 示例 demo 中缺少依赖
2. 优化 package.json 展示
=> fix: fix lack of  deps in demo

packages/x6/src/graph/hook.ts, packages/x6/src/graph/options.ts, packages/x6/src/style/raw.ts, packages/x6/src/view/node.ts
=> fix: 🐛 change port cursor style when is not magnet

packages/x6/package.json
=> fix: 🐛 src dir included in publication

packages/x6/src/model/cell.ts
=> fix: 🐛 don't change cell id when setProp

sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md
=> docs: 📚️ add faq

packages/x6/src/addon/scroller/index.less, packages/x6/src/graph/scroller.ts
perf: ⚡️ enhance scroller performance by avoid scoller reflow caused by changing classList
=> perf: ⚡️ enhance scroller performance by avoid scoller reflow caused by changing classList

packages/x6/src/graph/keyboard.ts
feat: ✨ postpone keyboard target focusing to improve dragging performance
=> feat: ✨ postpone keyboard target focusing to improve dragging performance

packages/x6/src/graph/keyboard.ts
=> fix: 🐛 add comment, want to release new version

packages/x6/src/graph/hook.ts
当拖动 source 更改连接时，validateConnection 实现有误，应该始终检测正在变更的一端的 magnet，和 `terminalView` 保持一致
=> fix: 🐛 check correct magnet in validateConnection

packages/x6/src/view/node.ts, sites/x6-sites/docs/api/graph/interaction.en.md, sites/x6-sites/docs/api/graph/interaction.zh.md, sites/x6-sites/docs/tutorial/basic/interacting.en.md, sites/x6-sites/docs/tutorial/basic/interacting.zh.md
1. 删除鼠标移入时的 validateEdge 调用
2. 优化相关文档
=> fix: 🐛 fix validateEdge trigger timming

packages/x6/src/registry/connector/jumpover.ts
=> fix: 🐛 add default route for createLines in jumpover

examples/x6-app-dag/package.json, examples/x6-app-draw/package.json, examples/x6-app-er/package.json, examples/x6-example-features/package.json
=> fix: 🐛 fix x6-react-components version in demo

examples/x6-example-features/src/pages/performance/matrix.tsx, examples/x6-example-features/src/pages/performance/v2.tsx, packages/x6-react-shape/src/view.ts, packages/x6-vue-shape/src/view.ts, packages/x6/src/graph/renderer.ts, packages/x6/src/util/array/array.ts, packages/x6/src/util/array/diff.ts, packages/x6/src/util/dom/attr.ts, packages/x6/src/util/dom/geom.ts, packages/x6/src/util/index.ts, packages/x6/src/util/scheduler/index.ts, packages/x6/src/util/string/format.ts, packages/x6/src/util/string/uuid.ts, packages/x6/src/view/attr.ts, packages/x6/src/view/cache.ts, packages/x6/src/view/cell.ts, packages/x6/src/view/view.ts
1. 任务方式异步渲染 svg 节点部分属性
2. 减少渲染边的 getBBox 和 getMatrix 调用
3. 节点排序逻辑优化
4. 增加缓存
=> perf: optimize SVG node rendering performance

packages/x6/src/view/attr.ts
=> fix: 🐛 revert delay text attr tmp

packages/x6/src/view/edge.ts
=> fix: 🐛 validateEdge is sync

packages/x6/src/graph/mousewheel.ts, packages/x6/src/graph/options.ts, packages/x6/src/graph/panning.ts, packages/x6/src/util/dom/core.ts, packages/x6/src/util/dom/mousewheel.ts, sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md
=> feat: ✨ panning support rightMouseDown and mousehwheel

packages/x6/src/graph/mousewheel.ts
=> fix: 🐛 fix can not scroller by mousewheel

packages/x6/src/graph/mousewheel.ts, packages/x6/src/graph/panning.ts, packages/x6/src/util/dom/mousewheel.ts
=> fix: 🐛 add onWheelGuard to prevent unwanted preventDefault

packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/options.ts, packages/x6/src/graph/renderer.ts, packages/x6/src/model/model.ts, packages/x6/src/util/dom/mousewheel.ts, sites/x6-sites/docs/tutorial/basic/selection.en.md, sites/x6-sites/docs/tutorial/basic/selection.zh.md, sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md
=> feat: ✨ add rubberNode and rubberEdge config

packages/x6/src/util/dom/text.ts
=> fix: 🐛 support css var in font-size

packages/x6/src/util/dom/geom.ts
=> fix: 🐛 fix getBBoxByElementAttr

packages/x6/src/view/attr.ts
=> fix: 🐛 only delay svg attr

packages/x6/src/view/cache.ts
=> fix: 🐛 revert getBoundingRect change

packages/x6/src/graph/graph.ts, sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md
=> docs: 📚️ deprecation getCell

packages/x6/src/model/node.ts
=> fix: 🐛 fix handledTranslation option passing to child node when translating

examples/x6-example-features/src/pages/scroller/index.tsx, packages/x6/src/graph/scroller.ts
=> feat: ✨ support panning scroller graph byrightmousedown

sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md
=> docs: 📚️ add demo for toSVG

sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
=> docs: 📚️ add faq for dnd

packages/x6-react-components/src/dropdown/index.tsx
=> fix: 🐛 fix x6-react-component release version

sites/x6-sites/docs/api/registry/attr.en.md, sites/x6-sites/docs/api/registry/attr.zh.md
=> docs: 📚️ fix refWidth2 demo

sites/x6-sites/docs/tutorial/intermediate/events.en.md, sites/x6-sites/docs/tutorial/intermediate/events.zh.md
修复文档：
blank:mouseenter -> graph:mouseenter
blank:mouseleave -> graph.mouseleave
=> docs: 📚️ fix blank:mouseenter event name

sites/x6-sites/docs/api/registry/grid.en.md, sites/x6-sites/docs/api/registry/grid.zh.md
=> docs: 📚️ optimize registerGrid dmeo

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
add `usePortal` React Hook doc.
=> docs: 📚️ add `usePortal` React Hook doc

packages/x6/src/addon/minimap/index.ts, packages/x6/src/graph/hook.ts, packages/x6/src/graph/minimap.ts, sites/x6-sites/docs/tutorial/basic/minimap.en.md, sites/x6-sites/docs/tutorial/basic/minimap.zh.md, sites/x6-sites/docs/tutorial/basic/scroller.en.md, sites/x6-sites/docs/tutorial/basic/scroller.zh.md
=> feat: ✨ support minimap in normal graph

README.en-us.md, README.md, packages/x6/README.md, sites/x6-sites/docs/api/registry/edge-tool.en.md, sites/x6-sites/docs/api/registry/edge-tool.zh.md, sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/about.zh.md, sites/x6-sites/docs/tutorial/contact.en.md, sites/x6-sites/docs/tutorial/contact.zh.md
=> docs: 📚️ update dingding code

packages/x6/src/model/cell.ts, sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md
=> fix: 🐛 optimize addTools params

sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md
=> docs: 📚️ change browser support detail

packages/x6/src/addon/scroller/index.ts
=> fix: 🐛 fix scroller content size when not autoResize

packages/x6/src/graph/background.ts
=> fix: 🐛 fix background size when not defined, fixed #1070

packages/x6/src/graph/selection.ts
=> fix: 🐛 not clean selection when mousedown

codecov.yml, packages/x6-vector/src/vector/filter/filter.test.ts, packages/x6-vector/src/vector/filter/filter.ts, packages/x6-vector/src/vector/gradient/linear.test.ts, packages/x6-vector/src/vector/gradient/radial.test.ts, packages/x6-vector/src/vector/marker/marker.test.ts
=> chore: 🛠️ config coverage color range

examples/x6-example-features/src/pages/group/data.json, examples/x6-example-features/src/pages/group/index.tsx, packages/x6/src/model/cell.ts
=> fix: 🐛 optimize cell remove method

packages/x6/src/view/node.ts
=> fix: 🐛 fix the embedded triggered source

packages/x6/src/view/node.ts
=> fix: 🐛 fix node:move event triggered source

examples/x6-example-features/src/pages/path/drawer/drawer.ts, examples/x6-example-features/src/pages/path/drawer/index.tsx
=> fix: 🐛 fix running error of x6-example-demo

packages/x6/src/graph/keyboard.ts
解决：https://github.com/antvis/X6/issues/1112
=> fix: 🐛 preventScroll when focus graph

packages/x6-react-shape/src/view.ts, packages/x6-vue-shape/src/view.ts
=> fix: 🐛 unmount component when node unmount

packages/x6/src/addon/scroller/index.ts
=> fix: 🐛 revert fix scroller content size

packages/x6/src/graph/panning.ts, packages/x6/src/view/node.ts
=> fix: 🐛 auto scroll graph when drag magnet

packages/x6-react-shape/src/view.ts, packages/x6-vue-shape/src/view.ts
=> fix: 🐛 revert add unmont method

packages/x6/src/model/edge.ts, packages/x6/src/model/node.ts, packages/x6/src/view/tool.ts
=> fix: 🐛 fix type definitions

packages/x6/src/view/cell.ts
增加 `toolsAddable` 配置，可以应用到以下场景：
1. 小地图：小地图上不应该出现工具
=> fix: 🐛 add toolsAddable config for interacting

packages/x6-geometry/README.md, packages/x6-vector/README.md, sites/x6-sites/gatsby-config.js, sites/x6-sites/package.json, yarn.lock
=> doc: update sites template

examples/x6-example-features/src/pages/group/data.json, examples/x6-example-features/src/pages/group/index.less, examples/x6-example-features/src/pages/group/index.tsx
=> docs: 📚️ add group demo

package-lock.json, package.json, packages/x6-angular-shape/README.md, packages/x6-angular-shape/package.json, packages/x6-angular-shape/rollup.config.js, packages/x6-angular-shape/src/hook.ts, packages/x6-angular-shape/src/index.ts, packages/x6-angular-shape/src/node.ts, packages/x6-angular-shape/src/registry.ts, packages/x6-angular-shape/src/view.ts, packages/x6-angular-shape/tsconfig.json, sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
#696 
Add angualr shape, it allow angualr user use angualr component or template as node to render.
=> feat: add angualr shape

packages/x6/src/graph/graph.ts, sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md
=> fix: 🐛 unified panning api

examples/x6-app-dag/src/layout/header/index.tsx, examples/x6-app-er/src/pages/ERGraph/Toolbar/index.tsx
=> docs: 📚️ delete design docs in demo

packages/x6-geometry/src/curve.ts, packages/x6-geometry/src/ellipse.ts, packages/x6-geometry/src/geometry.ts, packages/x6-geometry/src/line.ts, packages/x6-geometry/src/path/path.ts, packages/x6-geometry/src/point.test.ts, packages/x6-geometry/src/point.ts, packages/x6-geometry/src/polyline.ts, packages/x6-geometry/src/rectangle.test.ts, packages/x6-geometry/src/rectangle.ts, packages/x6-geometry/src/version.ts
=> test: ✅ update test specs

examples/x6-app-dag/src/pages/rx-models/experiment-graph.tsx
=> fix: 🐛 fix delete node connection not delete

sites/x6-sites/docs/tutorial/advanced/layout.en.md, sites/x6-sites/docs/tutorial/advanced/layout.zh.md
=> docs: 📚️ fix layout usage

packages/x6/src/view/edge.ts
=> style: 🎨 optimize find snap methods

packages/x6/src/view/edge.ts
=> fix: 🐛 revert optimze find snap elem

packages/x6/src/addon/scroller/index.ts, packages/x6/src/addon/selection/index.ts
1. 框选超过画布时自动滚动画布
2. 增加 scroller.widget.panning 事件
=> fix: 🐛 auto scroller when selection over graph

sites/x6-sites/examples/edge/tool/demo/meta.json
=> Fix menu spelling mistake

packages/x6/src/graph/transform.ts, sites/x6-sites/docs/api/graph/transform.en.md, sites/x6-sites/docs/api/graph/transform.zh.md
ScaleContentToFitOptions 中 padding 支持 SideOptions 类型
=> fix: 🐛 change type of padding in ScaleContentToFitOptions

packages/x6/src/addon/stencil/index.ts
=> fix: 🐛 Stencil searches are case sensitive

packages/x6/src/model/cell.ts
=> fix: 🐛 remove prop not remove attr

packages/x6/src/addon/selection/index.ts
解决 resizing 的时候，触发 selecting 中事件中移动事件监听，导致节点被移动多次的问题。
=> fix: 🐛 translateSelected nodes exclude self

sites/x6-sites/docs/api/graph/graph.en.md, sites/x6-sites/docs/api/graph/graph.zh.md
=> docs: 📚️ add doc for panning

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> docs: Update ISSUE_TEMPLATE

packages/x6/src/model/cell.ts
Close https://github.com/antvis/X6/issues/1195
=> fix: 🐛 optimize get child method

packages/x6-vue-shape/src/view.ts
=> fix(x6-vue-shape): clear vue instance

packages/x6/src/model/cell.ts
```ts
import { Node, Graph } from '@antv/x6'
interface Prop extends Node.Properties {
testProp: string;
data: {
id: number;
}
}
// 这样类型之后，开发的时候可以通过 `type guard`（https://www.typescriptlang.org/docs/handbook/advanced-types.html#instanceof-type-guards） 获取到当前结点的 `data` 属性类型
export default class EleFan extends Node<Prop> {
// 省略实现细节
}
Graph.registerNode('EleFan', EleFan)
```
```ts
interface Data: { num: number }
const data = node.getData<Data>();
node.setData<Data>({ num: 1 })
```
=> feat: 🎸 为定义业务数据的 data 属性提供类型定义

sites/x6-sites/examples/showcase/practices/demo/flowchart.ts, sites/x6-sites/examples/showcase/practices/demo/meta.json
=> docs: 📚️ add flow chart demo

sites/x6-sites/examples/edge/connector/demo/curve.ts
=> docs: 📚️ update curve demo

packages/x6-react-shape/src/wrap.ts
使用requestAnimationFrame来减少React Node render
React shape node 在node position和size 更新时会触发多次render，实际并没有必要
=> feat(react-shape): ✨ add throttle to size and position

packages/x6/src/addon/clipboard/index.ts
fix option merge order in paste
=> fix: 🐛 fix option merge order in paste

sites/x6-sites/examples/edge/tool/demo/meta.json, sites/x6-sites/examples/edge/tool/demo/tooltip.tsx
1. 解决 edge tooltip 在移动 edge 的时候 dom 重复创建问题
2. 优化 edge 样式
=> docs: 📚️ update edge tooltip dmeo

sites/x6-sites-demos-helper/scripts/speedup.js, sites/x6-sites/examples/edge/tool/demo/tooltip.tsx
修改 speedup 中查找 react-script 的路径
=> fix: 🐛 change home path in speedup js

.github/workflows/auto-close-fixed-issues.yml, .github/workflows/auto-comment.yml, .github/workflows/backup/auto-assign.yml, .github/workflows/ci.yml, .github/workflows/create-issue-branch.yml, .github/workflows/delete-stale-releases.yml, .github/workflows/deploy-sites.yml, .github/workflows/label-commands.yml, .github/workflows/lock.yml, .github/workflows/needs-more-info.yml, .github/workflows/potential-duplicates.yml, .github/workflows/pr-label-branch-name.yml, .github/workflows/pr-label-file-paths.yml, .github/workflows/pr-label-patch-size.yml, .github/workflows/pr-label-status-dummy.yml, .github/workflows/pr-label-status.yml, .github/workflows/pr-label-title-body.yml, .github/workflows/preview.yml, .github/workflows/rebase.yml, .github/workflows/release.yml, .github/workflows/report-monthly.yml, .github/workflows/report-weekly.yml, .github/workflows/slash-commands.yml, .github/workflows/stale.yml, .github/workflows/sync-labels.yml, .github/workflows/update-authors.yml, .github/workflows/update-contributors.yml, .github/workflows/update-license.yml, .github/workflows/welcome.yml
=> ci: 👷 update workflow author

sites/x6-sites/docs/tutorial/basic/group.en.md, sites/x6-sites/docs/tutorial/basic/group.zh.md
=> docs: fix typo

packages/x6/src/addon/transform/index.ts
Resolve the rotation node error on the mobile terminal
=> fix: 🐛 normalize event before get clientX

packages/x6/src/addon/stencil/index.ts, sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
1. 增加 stencil 的 resizeGroup 方法
2. 优化 dnd 的文档
=> feat: ✨ add resizeGroup for stencil

packages/x6/src/graph/background.ts
draw multiple times to show the last image. Close #1294
=> fix: 🐛 draw background multiple times to show the last image

sites/x6-sites/docs/tutorial/log.en.md, sites/x6-sites/docs/tutorial/log.zh.md
=> docs: 📚️ update logs

examples/x6-example-features/src/pages/edge/edge-editor.tsx, sites/x6-sites/examples/showcase/practices/demo/meta.json, sites/x6-sites/examples/showcase/practices/demo/path-editor.ts
=> docs: 📚️ add path-editor demo

packages/x6/src/registry/attr/text.ts
=> fix: 🐛 modify the font size even if the text does not change

sites/x6-sites/examples/showcase/practices/demo/meta.json
=> docs: 📚️ fix filename of path-editor

packages/x6-angular-shape/src/view.ts
=> feat: ✨ Angular Component支持使用setData进行更新

sites/x6-sites/examples/showcase/practices/demo/flowchart.ts, sites/x6-sites/examples/showcase/practices/demo/meta.json
docs: 📚️ optimize flow chart demo
=> docs: 📚️ optimize flow chart demo

examples/x6-example-features/src/pages/case/er.tsx, sites/x6-sites/examples/data/er.json, sites/x6-sites/examples/showcase/practices/demo/class.ts, sites/x6-sites/examples/showcase/practices/demo/er.ts, sites/x6-sites/examples/showcase/practices/demo/meta.json, sites/x6-sites/package.json, yarn.lock
=> docs: 📚️ add er demo

examples/x6-example-features/src/pages/case/bpmn.tsx, sites/x6-sites/examples/data/bpmn.json, sites/x6-sites/examples/showcase/practices/demo/bpmn.ts, sites/x6-sites/examples/showcase/practices/demo/class.ts, sites/x6-sites/examples/showcase/practices/demo/dag.tsx, sites/x6-sites/examples/showcase/practices/demo/er.ts, sites/x6-sites/examples/showcase/practices/demo/flowchart.ts, sites/x6-sites/examples/showcase/practices/demo/meta.json
=> docs: 📚️ add bpmn demo

examples/x6-example-features/src/pages/case/mind.less, examples/x6-example-features/src/pages/case/mind.tsx, sites/x6-sites/examples/showcase/practices/demo/bpmn.ts, sites/x6-sites/examples/showcase/practices/demo/dag.tsx, sites/x6-sites/examples/showcase/practices/demo/meta.json, sites/x6-sites/examples/showcase/practices/demo/mindmap.ts
=> docs: 📚️ add mindmap demo

examples/x6-example-features/src/pages/case/mind.less, examples/x6-example-features/src/pages/case/mind.tsx, sites/x6-sites/examples/edge/tool/demo/context-menu.tsx, sites/x6-sites/examples/edge/tool/demo/meta.json, sites/x6-sites/examples/showcase/practices/demo/meta.json
=> docs: 📚️ update contextmenu demo

sites/x6-sites/docs/tutorial/intermediate/custom-edge.en.md, sites/x6-sites/docs/tutorial/intermediate/custom-edge.zh.md
=> docs: :memo: update custom-dege

sites/x6-sites/docs/tutorial/basic/edge.en.md, sites/x6-sites/docs/tutorial/basic/edge.zh.md
=> docs: 📝 update edge

packages/x6-vector/package.json, sites/x6-sites/examples/animation/smil/demo/meta.json, sites/x6-sites/examples/layout/general/demo/circle.ts, sites/x6-sites/examples/layout/general/demo/dagre.ts, sites/x6-sites/examples/layout/general/demo/ellipse.ts, sites/x6-sites/examples/layout/general/demo/force.ts, sites/x6-sites/examples/layout/general/demo/grid.ts, sites/x6-sites/examples/layout/general/demo/meta.json, sites/x6-sites/examples/layout/tree/demo/meta.json, sites/x6-sites/examples/layout/tree/demo/mindmap.ts
=> docs: 📚️ update layout demos

packages/x6-react-components/package.json
latest react-color  is not working, need  resolute to 2.17.3
=> fix: fix react-color version to avoid bug

sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md
=> docs: 📚️ update model

examples/x6-example-features/src/pages/tools/port-tooltip.tsx, sites/x6-sites/examples/node/tool/demo/meta.json, sites/x6-sites/examples/node/tool/demo/port-tooltip.tsx
=> docs: 📚️ add port tooltip demo

examples/x6-example-features/src/pages/case/swimlane.tsx, sites/x6-sites/examples/data/swimlane.json, sites/x6-sites/examples/showcase/practices/demo/meta.json, sites/x6-sites/examples/showcase/practices/demo/mindmap.ts, sites/x6-sites/examples/showcase/practices/demo/swimlane.ts
=> docs: 📚️ add swimlane demo

packages/x6-react-components/package.json
=> fix: 🐛 revert react-color version

sites/x6-sites/examples/animation/smil/demo/animateAlongPath.ts, sites/x6-sites/examples/animation/smil/demo/flashing.ts, sites/x6-sites/examples/animation/smil/demo/meta.json
=> docs: 📚️ update animation demo

packages/x6-react-components/package.json
fix: resolve react-color version to avoid bug
=> fix: resolve react-color version to avoid bug

README.en-us.md, README.md
=> docs: 📚️ update readme

sites/x6-sites/examples/showcase/faq/demo/meta.json
Change "validattion" to "validation".
Correct spelling makes documentation more attractive and readable.
=> fix English typo in example gallery

packages/x6/src/model/cell.ts
=> fix: 🐛 get children or parent delay

packages/x6/src/graph/scroller.ts
Close https://github.com/antvis/X6/issues/1635
=> fix: 🐛 listen mousedown event on scroller container

packages/x6/src/registry/tool/segments.ts, packages/x6/src/registry/tool/vertices.ts, sites/x6-svg-to-shape/package.json
=> fix: 🐛 fix lint error

packages/x6/package.json, sites/x6-sites/package.json
=> fix: 🐛 release x6 v1.28.2

packages/x6/package.json, sites/x6-sites-demos/package.json
=> fix: 🐛 update x6 version

packages/x6-vector/package.json, packages/x6/package.json
=> fix: 🐛 update x6-vector version

packages/x6-vector/package.json, packages/x6-vector/src/global/version.ts, packages/x6/package.json, packages/x6/src/global/version.ts
update x6 and x6-vector version
=> feat: ✨ update x6 and x6-vector version

.github/ISSUE_TEMPLATE/bug_report_zh.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request_zh.yml
add bug and feature template for chinese
=> chore: 🔧 add bug and feature template for chinese

.github/ISSUE_TEMPLATE/feature_request_zh.yml
=> chore: 🔧 fix feature template

.github/ISSUE_TEMPLATE/bug_report_zh.yml
=> chore: 🔧 update new bug template

sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md
Close https://github.com/antvis/X6/issues/1657
=> docs: 📚️ add qa for export image

README.en-us.md, README.md
=> docs: 📚️ update qrcode

packages/x6/src/geometry/curve.ts, packages/x6/src/geometry/line.ts
Close https://github.com/antvis/X6/issues/1681
=> fix: 🐛 add exception check for isLine and isCurve

sites/x6-sites/examples/showcase/practices/demo/flowchart.ts, sites/x6-sites/site/pages/index.zh.tsx
=> docs: 📚️ update websites logo

sites/x6-sites/docs/tutorial/basic/history.en.md, sites/x6-sites/docs/tutorial/basic/history.zh.md
=> docs: update history  zh / en

sites/x6-sites/docs/api/model/edge.en.md, sites/x6-sites/docs/api/model/edge.zh.md
=> docs: 📚️ fix docs error

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> docs: 优化vue渲染文档说明

sites/x6-sites-demos/packages/api/ui/menubar/basic/src/app.tsx
=> docs: 📚️ update menu demo

packages/x6/src/model/model.ts
Change "specipied" to "specified".
Correct spelling makes documentation more attractive and readable.
=> fix: fix typo in model

sites/x6-sites/docs/api/registry/node-tool.en.md, sites/x6-sites/docs/api/registry/node-tool.zh.md
=> doc: node-editor cell->nodeFix node editor

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> docs: 📚️ update react node docs

packages/x6/src/addon/dnd/index.less
=> fix: 🐛 add zindex for x6-widget-dne

sites/x6-sites/examples/node/tool/demo/editable.ts
=> docs: 📚️ update cell editor demo

sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
=> docs: 📚️ update dnd docs

packages/x6/src/graph/graph.ts, packages/x6/src/model/model.ts, sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md
=> fix: 🐛 add updateCellId api

packages/x6/src/addon/scroller/index.ts, packages/x6/src/graph/panning.ts
stop panning when mouseleave body
=> fix: 🐛 stop panning when mouseleave body

packages/x6/src/model/model.ts
change startBatch to stopBatch
=> fix: 🐛 change startBatch to stopBatch

packages/x6-angular-shape/src/view.ts, packages/x6-react-shape/src/view.ts, packages/x6-vue-shape/src/view.ts
dispose components when unmount,maybe a break change.
=> feat: ✨ dispose components when unmount

packages/x6-vue-shape/src/view.ts
change vue vm instance in vue3
=> fix: 🐛 change vue vm instance

packages/x6/src/model/edge.ts, packages/x6/src/model/node.ts, packages/x6/src/registry/router/manhattan/options.ts, sites/x6-sites/docs/api/model/node.en.md, sites/x6-sites/docs/api/model/node.zh.md
=> feat: ✨ add insertPort api

packages/x6/src/registry/tool/editor.ts, sites/x6-sites-demos/packages/api/registry/node-tool/editor/src/app.tsx, sites/x6-sites/examples/node/tool/demo/editable.ts
not create label when text is empty
=> fix: 🐛 not create label when text is empty

.github/workflows/sync-to-gitee.yml
=> chore: 🔧 update sync-to-gitee

.github/workflows/sync-to-gitee.yml
=> chore: 🔧 update sync-to-gitee.yml

packages/x6/src/addon/minimap/index.ts
1. fix source graph and target graph not updating synchronously when transform in panning mode
2. https://github.com/antvis/X6/pull/1819
=> fix: 🐛 fix source graph and target graph not updating synchronously

sites/x6-sites/docs/api/registry/edge-tool.en.md, sites/x6-sites/docs/api/registry/edge-tool.zh.md, sites/x6-sites/docs/api/registry/node-tool.en.md, sites/x6-sites/docs/api/registry/node-tool.zh.md
1. add `markup` and `onClick` option for `button-remove` tool
=> docs: 📚️ update node-tool doc

sites/x6-sites/docs/tutorial/advanced/layout.en.md, sites/x6-sites/docs/tutorial/advanced/layout.zh.md
Add documentation to the layout process.
=> docs: 📚️ add layout process explain

sites/x6-sites/docs/api/graph/graph.en.md, sites/x6-sites/docs/api/graph/graph.zh.md
=> docs:fix api graph description

sites/x6-sites/docs/tutorial/basic/edge.en.md, sites/x6-sites/docs/tutorial/basic/edge.zh.md, sites/x6-sites/docs/tutorial/intermediate/custom-edge.en.md, sites/x6-sites/docs/tutorial/intermediate/custom-edge.zh.md
=> docs: fix edge and custom-edge doc

packages/x6/src/registry/tool/editor.ts
optimize setText for edge-editor
=> fix: 🐛 optimize setText for edge-editor

packages/x6/src/registry/tool/editor.ts
=> feat: 🐛　support click on the non-text area without adding a new label

packages/x6/src/registry/tool/editor.ts
=> fix: 🐛 fix cellEditorOptions typo

sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/about.zh.md, sites/x6-sites/docs/tutorial/contact.en.md, sites/x6-sites/docs/tutorial/contact.zh.md
docs: update doc about and contact
=> docs: update doc about and contact

examples/x6-example-features/src/pages/case/dag.tsx, examples/x6-example-features/src/pages/case/elk.tsx, examples/x6-example-features/src/pages/edge/tooltip.tsx, examples/x6-example-features/src/pages/embed/nested2.tsx, examples/x6-example-features/src/pages/graph/attribute-card.tsx, examples/x6-example-features/src/pages/graph/background-card.tsx, examples/x6-example-features/src/pages/graph/bbox-card.tsx, examples/x6-example-features/src/pages/graph/fit-card.tsx, examples/x6-example-features/src/pages/graph/grid-card.tsx, examples/x6-example-features/src/pages/graph/index.tsx, examples/x6-example-features/src/pages/graph/scale-card.tsx, examples/x6-example-features/src/pages/issues/520.tsx, examples/x6-example-features/src/pages/issues/531.tsx, examples/x6-example-features/src/pages/issues/537.tsx, examples/x6-example-features/src/pages/issues/627.tsx, examples/x6-example-features/src/pages/measurement/angle-shape.ts, examples/x6-example-features/src/pages/org/index.tsx, examples/x6-example-features/src/pages/path/random.tsx, examples/x6-example-features/src/pages/performance/async.tsx, examples/x6-example-features/src/pages/react/table/component.tsx, examples/x6-example-features/src/pages/router/index.tsx, examples/x6-example-features/src/pages/shape/xml-markup.tsx, examples/x6-example-features/src/pages/tools/contextmenu.tsx, examples/x6-example-features/src/pages/undo/index.tsx, packages/x6/src/util/unit/index.test.ts
=> style: 🎨 fix lint error

packages/x6/src/registry/tool/editor.ts
=> fix: 🐛 change the order of statement

AUTHORS, SECURITY.md, packages/x6/src/registry/tool/editor.ts
=> docs: add security policy

packages/x6/src/util/object/inherit.ts
1. delete the new Function mode to avoid the CSP policy
2. Methods are provided by @OpportunityLiu (https://github.com/OpportunityLiu)https://github.com/antvis/X6/pull/1266#issuecomment-906905929
=> feat: ✨ delete the new Function mode to avoid the CSP policy

packages/x6-common/package.json, packages/x6-common/tsconfig.json, packages/x6-geometry/package.json, packages/x6-geometry/src/version.ts, packages/x6-geometry/tsconfig.json, scripts/build-dev, yarn.lock
1. exclude __test__ dir in tsconfig.ts
=> chore: 🔧 only include src in tsconfig

packages/x6-next/README.md, packages/x6-next/__tests__/version.test.ts, packages/x6-next/index.ts, packages/x6-next/karma.conf.js, packages/x6-next/package.json, packages/x6-next/rollup.config.js, packages/x6-next/scripts/readme.js, packages/x6-next/scripts/style.js, packages/x6-next/src/index.less, packages/x6-next/src/index.ts, packages/x6-next/src/style/index.less, packages/x6-next/src/style/raw.ts, packages/x6-next/src/style/themes/default.less, packages/x6-next/src/style/themes/index.less, packages/x6-next/src/version.ts, packages/x6-next/tsconfig.json
=> feat: ✨ init x6-next repo

packages/x6-common/src/dom/matrix.ts, packages/x6-common/src/dom/text.ts, packages/x6-common/src/event/events.ts, packages/x6-common/src/registry/registry.ts, packages/x6-common/src/types.ts, packages/x6-common/src/vector/index.ts
=> chore: 🔧 unnamespace the types

packages/x6-common/package.json, packages/x6-common/src/dom/event/core.ts, packages/x6-common/src/dom/event/hook.ts, packages/x6-common/src/dom/event/listener.ts, packages/x6-common/src/dom/event/main.ts, packages/x6-common/src/dom/event/object.ts, packages/x6-common/src/dom/event/store.ts, packages/x6-common/src/dom/event/types.ts, packages/x6-common/src/event/events.ts, packages/x6-common/src/registry/registry.ts, packages/x6-common/src/types.ts, packages/x6-common/src/vector/index.ts, packages/x6-geometry/src/ellipse.ts, packages/x6-geometry/src/line.ts, packages/x6-geometry/src/path/close.ts, packages/x6-geometry/src/path/path.ts, packages/x6-geometry/src/path/segment.ts, packages/x6-geometry/src/rectangle.ts, tsconfig.json
add importsNotUsedAsValues tsconfig
=> chore: 🔧 add importsNotUsedAsValues tsconfig

packages/x6-common/src/dom/event/core.ts, packages/x6-common/src/dom/event/hook.ts, packages/x6-common/src/dom/event/index.ts, packages/x6-common/src/dom/event/listener.ts, packages/x6-common/src/dom/event/main.ts, packages/x6-common/src/dom/event/object.ts, packages/x6-common/src/dom/event/store.ts, packages/x6-common/src/dom/event/types.ts, packages/x6-common/src/dom/event/util.ts, packages/x6-common/src/dom/matrix.ts, packages/x6-common/src/dom/text.ts, packages/x6-common/src/event/events.ts, packages/x6-common/src/registry/registry.ts, packages/x6-common/src/size-sensor/index.ts, packages/x6-common/src/size-sensor/sensors/object.ts, packages/x6-common/src/size-sensor/sensors/observer.ts, packages/x6-common/src/vector/index.ts, packages/x6-geometry/src/ellipse.ts, packages/x6-geometry/src/geometry.ts, packages/x6-geometry/src/line.ts, packages/x6-geometry/src/path/close.ts, packages/x6-geometry/src/path/path.ts, packages/x6-geometry/src/path/segment.ts, packages/x6-geometry/src/point.ts, packages/x6-geometry/src/rectangle.ts, packages/x6-geometry/src/util.ts
=> chore: 🔧 replace import type to import

packages/x6-common/__tests__/dom/data.test.ts, packages/x6-common/src/dom/data.ts, packages/x6-common/src/dom/main.ts
=> feat: ✨ add dom data methods

packages/x6-vue-shape/src/view.ts
x6 删除 vue3 自定义节点，调用 `app.unmount` 之前，重置了 container 的 innerHTML，导致 vue 组件 unmount 的时候，fragment 删除报错
resolve #1973
=> fix(x6-vue-shape): 🐛 error on removing fragment node

packages/x6-vector/src/dom/common/adopter.ts, packages/x6/src/util/object/object.ts
=> fix: 🐛 fix lgtm alert

packages/x6/src/graph/format.ts
Close https://github.com/antvis/X6/issues/1871
=> fix: 🐛 change copystyle not include number propery when toSvg

sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md, sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md, sites/x6-sites/docs/api/model/node.en.md, sites/x6-sites/docs/api/model/node.zh.md, sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md
=> docs: update doc api

examples/x6-example-features/src/pages/tools/tooltip.tsx, packages/x6-common/__tests__/dom/event.test.ts, packages/x6-vector/src/dom/common/adopter.ts, packages/x6-vue-shape/src/view.ts, packages/x6/src/addon/scroller/index.ts, packages/x6/src/graph/format.ts, packages/x6/src/util/dom/geom.ts, scripts/monorepo-semantic-release/yarn.lock, sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md, sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md, sites/x6-sites/docs/api/model/node.en.md, sites/x6-sites/docs/api/model/node.zh.md, sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md, sites/x6-sites/examples/edge/tool/demo/tooltip.tsx, yarn.lock
=> feat: sync code from master

examples/x6-example-features/src/pages/v2/1.tsx, examples/x6-example-features/src/pages/v2/2.tsx, examples/x6-example-features/src/pages/v2/data.ts, packages/x6-core/src/index.ts, packages/x6-core/src/renderer/index.ts, packages/x6-core/src/renderer/options.ts, packages/x6-core/src/renderer/renderer.ts, packages/x6-core/src/schedule/index.ts, packages/x6-core/src/schedule/schedule.ts, packages/x6-core/src/view/node.ts, packages/x6-next/src/graph/events.ts, packages/x6-next/src/graph/graph.ts, scripts/build-dev
expose renderer interface in x6-core
=> refactor: ♻️ expose renderer interface in x6-core

sites/x6-sites/docs/tutorial/epilog.en.md, sites/x6-sites/docs/tutorial/epilog.zh.md
=> docs: correct code mistake

examples/x6-example-features/src/pages/v2/1.tsx, scripts/build-dev
build x6-vector when bootstrap to fix test error
=> chore: 🔧 build x6-vector when bootstrap to fix test error

sites/x6-sites/examples/node/custom-node/demo/custom-with-svg.ts
optimize custom node demo. Close https://github.com/antvis/X6/issues/2056
=> docs: 📚️ optimize custom node demo

examples/x6-example-features/src/pages/v2/1.tsx, packages/x6-core/src/view/node.ts
check whether label existed in port
=> perf: ⚡️ check whether label existed in port

sites/x6-sites/docs/tutorial/intermediate/custom-edge.en.md, sites/x6-sites/docs/tutorial/intermediate/custom-edge.zh.md
docs: update doc error .Close #2066
=> docs: update doc error

sites/x6-sites/docs/tutorial/basic/selection.en.md, sites/x6-sites/docs/tutorial/basic/selection.zh.md
add selection options description
=> docs: 📚️ add selection options description

packages/x6-common/package.json, packages/x6-core/package.json, packages/x6-geometry/package.json, packages/x6-next/package.json, packages/x6-vector/package.json
delete browserslist config, related to https://github.com/antvis/X6/pull/2084
=> chore: 🔧 delete browserslist config

packages/x6/src/graph/graph.ts
x6画布缩放方法 zoomTo 并没有返回画布实例，与文档表现不一。
已修复
=> fix: :bug: fix the graph function zoomTo not return the graph instance.

examples/x6-example-features/src/pages/v2/1.tsx, packages/x6-core/src/model/cell.ts, packages/x6-core/src/model/collection.ts, packages/x6-core/src/model/edge.ts, packages/x6-core/src/view/edge.ts, packages/x6-core/src/view/flag.ts, packages/x6-core/src/view/markup.ts, packages/x6-core/src/view/tool.ts, packages/x6-next/src/graph/graph.ts
=> refactor: ♻️ remove toolsMarkup options

packages/x6-vector/src/vector/image/image.test.ts, packages/x6/src/addon/minimap/index.ts, packages/x6/src/graph/mousewheel.ts, packages/x6/src/graph/panning.ts, packages/x6/src/graph/transform.ts
unified minimap interaction between scroller and panning
=> feat: ✨ unified minimap interaction between scroller and panning

packages/x6/src/addon/minimap/index.ts
Close https://github.com/antvis/X6/issues/2116
=> fix: 🐛 fix minimap error in after resize graph

packages/x6-core/src/model/edge.ts, packages/x6-core/src/view/attr.ts, packages/x6-core/src/view/edge.ts, packages/x6-core/src/view/flag.ts, packages/x6-core/src/view/markup.ts, packages/x6-core/src/view/node.ts, packages/x6-vector/src/vector/image/image.test.ts
=> refactor: ♻️ remove functions related to string markup

.github/workflows/ci.yml, .github/workflows/deploy-sites.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/update-cache.yaml
update node versio for workflow
=> chore: 🔧 update node versio for workflow

sites/x6-sites/docs/tutorial/advanced/layout.en.md, sites/x6-sites/docs/tutorial/advanced/layout.zh.md
1. Add `begin` option for dagre layout
2. Modify the description of align option
=> docs: 📚️ optimize dagre options

examples/x6-example-features/src/pages/v2/render.tsx, packages/x6-core/src/renderer/renderer.ts, packages/x6-core/src/scheduler/queueJob.ts, packages/x6-core/src/scheduler/scheduler.ts, packages/x6-core/src/view/cell.ts, packages/x6-next/src/graph/graph.ts, packages/x6-next/src/graph/grid.ts, packages/x6-next/src/graph/virtual-render.ts
=> feat: ✨ add virtual render feature

packages/x6-core/src/scheduler/scheduler.ts
1. add view sorting feature
2. add view show and hide feature
=> feat: ✨ add view sorting and display feature

sites/x6-sites/docs/api/graph/model.zh.md
=> docs: Change the getCellById method parameter name

packages/x6/src/util/dom/attr.ts
增加常见的大小写敏感属性：
```ts
const CASE_SENSITIVE_ATTR = [
'viewBox',
'attributeName',
'attributeType',
'repeatCount',
]
```
=> fix: 🐛 add some case sensitive attr

.github/workflows/pr-label-status.yml
Fixes a malfunctioning workflow due to a misconfiguration, which is due to a documentation error. See wow-actions/pr-triage#18.
=> chore: 🔧 fix malfunctioning github workflow

examples/x6-example-features/src/pages/v2/clock.tsx, examples/x6-example-features/src/pages/v2/graph.tsx, examples/x6-example-features/src/pages/v2/index.less, examples/x6-example-features/src/pages/v2/index.tsx, packages/x6-common/src/dom/text.ts, packages/x6-core/src/registry/attr/text.ts
optimize breakText for a high performance version
=> perf: ⚡️ optimize breakText for a high performance version

packages/x6/src/addon/minimap/index.ts
=> feat: ✨ 🎸 panning mode support for minimap

packages/x6/src/graph/hook.ts
1.  When judging nodes, the influence of the ports should be excluded, because the ports and nodes have the same terminalView
=> fix: 🐛 fix allowNode option affects port connections

.github/workflows/gitleaks.yml
pin gitleaks-actions to v1.6.0
=> chore: 🔧 pin gitleaks-actions to v1.6.0

packages/x6/package.json, packages/x6/src/addon/selection/index.ts, packages/x6/src/global/version.ts, packages/x6/src/view/edge.ts, packages/x6/src/view/node.ts
1. code format
2. update version to 1.32.4
=> chore: 🔧 code format and update version

packages/x6/package.json, packages/x6/src/global/version.ts
=> chore: 🔧 update version in package.json

sites/x6-sites/docs/tutorial/intermediate/custom-node.en.md
=> docs: recorrect the docs of custom-node

packages/x6-common/package.json, packages/x6-core/package.json, packages/x6-geometry/package.json, packages/x6-next/package.json, packages/x6-next/src/version.ts, packages/x6-react-shape/package.json, packages/x6-react-shape/src/view.ts, packages/x6-react-shape/src/wrap.tsx, packages/x6-vue-shape/package.json, packages/x6-vue-shape/src/teleport.ts, packages/x6-vue-shape/src/view.ts, yarn.lock
=> chore: 🔧 update package version

packages/x6/src/view/node.ts
=> fix: 🐛 Fixed the bug that node can't be draging.

packages/x6/package.json, packages/x6/src/global/version.ts, packages/x6/src/view/node.ts
=> chore: 🔧 update x6 version

packages/x6/src/graph/keyboard.ts
=> fix: fix global keyboard event is invalid in some case

.github/workflows/gitleaks.yml
reduce the version gitleaks-actions to 1.6.0
=> chore: 🔧 reduce the version gitleaks-actions to 1.6.0

packages/x6/src/view/node.ts
add x6-port-groupName class for port container, for example:
```ts
ports: [{
id: 'port1',
group: 'test'
}]
```
then port container will have a classname x6-port-test
=> fix: 🐛 add x6-port-groupName class for port container

packages/x6/src/registry/router/manhattan/obstacle-map.ts, packages/x6/src/registry/router/manhattan/options.ts, sites/x6-sites/docs/api/registry/router.en.md, sites/x6-sites/docs/api/registry/router.zh.md
=> feat: ✨ #2333 Set excludeNodes for manhattan args

packages/x6/src/graph/clipboard.ts, packages/x6/src/graph/events.ts, sites/x6-sites/docs/tutorial/basic/clipboard.en.md, sites/x6-sites/docs/tutorial/basic/clipboard.zh.md
=> feat: ✨ add clipboard:changed event

packages/x6/src/shape/base.ts
set visible true when init cells
=> fix: 🐛 set visible true when init cells

packages/x6/src/addon/snapline/index.ts
=> fix: 🐛 snapline constructor init offset close #2318

packages/x6/src/registry/router/manhattan/options.ts, sites/x6-sites/docs/api/registry/router.en.md, sites/x6-sites/docs/api/registry/router.zh.md
support padding options for manhattan router
=> feat: ✨ support padding options for manhattan router

packages/x6/src/view/node.ts
fix embeded event trigger error
=> fix: 🐛 fix embeded event trigger error

packages/x6/src/addon/transform/index.ts
=> fix: 🐛 normalize angle when rotating

packages/x6/src/graph/options.ts, packages/x6/src/graph/selection.ts, sites/x6-sites/docs/api/graph/selecting.en.md, sites/x6-sites/docs/api/graph/selecting.zh.md, sites/x6-sites/docs/tutorial/basic/selection.en.md, sites/x6-sites/docs/tutorial/basic/selection.zh.md
=> feat: support shift key multi-selection

packages/x6/src/addon/snapline/index.less
=> fix: fix selection box incorrect position when enable snapline

packages/x6-react-shape/package.json, packages/x6/package.json, packages/x6/src/global/version.ts, packages/x6/src/style/raw.ts, packages/x6/src/util/unit/index.test.ts
include src to x6-react-shape build files
=> chore: 🔧 include src to x6-react-shape build files

.github/workflows/auto-close-fixed-issues.yml, .github/workflows/auto-comment.yml, .github/workflows/ci.yml, .github/workflows/create-issue-branch.yml, .github/workflows/delete-stale-releases.yml, .github/workflows/deploy-sites.yml, .github/workflows/gitleaks.yml, .github/workflows/label-commands.yml, .github/workflows/lock.yml, .github/workflows/needs-more-info.yml, .github/workflows/potential-duplicates.yml, .github/workflows/pr-label-branch-name.yml, .github/workflows/pr-label-file-paths.yml, .github/workflows/pr-label-patch-size.yml, .github/workflows/pr-label-status-dummy.yml, .github/workflows/pr-label-status.yml, .github/workflows/pr-label-title-body.yml, .github/workflows/preview.yml, .github/workflows/rebase.yml, .github/workflows/release.yml, .github/workflows/slash-commands.yml, .github/workflows/stale.yml, .github/workflows/sync-labels.yml, .github/workflows/sync-to-gitee.yml, .github/workflows/update-authors.yml, .github/workflows/update-cache.yaml, .github/workflows/update-contributors.yml, .github/workflows/update-license.yml, .github/workflows/welcome.yml
Add comments to GitHub actions (in `.github/workflows`) explaining what each of them does.
... so that new contributors could understand better how the repo functions.
=> chore: 🔧 comment GitHub actions

packages/x6/src/graph/keyboard.ts
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
- [ x ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
=> fix: Enhance  isinputevent method

sites/x6-sites/docs/api/registry/edge-tool.en.md, sites/x6-sites/docs/api/registry/edge-tool.zh.md
=> docs: 📖　the tool of edge documentation update

packages/x6/package.json, packages/x6/src/global/version.ts, sites/x6-sites-demos/package.json, sites/x6-sites/package.json
=> chore: 🔧 change x6 version

configs/package-json/cli.json, packages/x6/package.json, yarn.lock
=> chore: 🔧 add release script

packages/x6/package.json, packages/x6/src/global/version.ts
=> chore: 🔧 change release commit message

packages/x6-common/package.json, packages/x6-geometry/package.json, packages/x6-next/package.json
=> chore: 🔧 update commit msg for release

packages/x6-geometry/package.json
release @antv/x6-geometry@2.0.1-beta.4
=> chore: 🔧 release @antv/x6-geometry@2.0.1-beta.4

packages/x6-next/src/version.ts
=> chore: 🔧 update x6-next version

packages/x6/src/graph/options.ts, packages/x6/src/graph/view.ts
=> feat: ✨ preventDefaultContextMenu support function

packages/x6-vue-shape/package.json
=> fix: 升级vue-demi版本

sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md
=> docs: add some methods for model documentation

README.md
Just fix a typo in README.md: CND => CDN.
None
=> docs(README.md): fix typo of CDN

packages/x6-vue-shape/package.json
=> chore: 🔧 add release-it

packages/x6-vue-shape/package.json
=> chore: 🔧 update git tag for release-it

packages/x6/package.json, packages/x6/src/addon/selection/index.ts, packages/x6/src/graph/renderer.ts, packages/x6/src/model/edge.ts, packages/x6/src/model/model.ts
Close https://github.com/antvis/X6/issues/2465
Close https://github.com/antvis/X6/issues/2466
Close https://github.com/antvis/X6/issues/2464
=> fix: fix some issue

packages/x6/src/global/version.ts, sites/x6-sites/docs/tutorial/basic/interacting.zh.md
specify createEdge description
=> docs: 📚️ specify createEdge description

packages/x6/src/addon/snapline/index.ts, packages/x6/src/graph/graph.ts, sites/x6-sites/docs/tutorial/basic/snapline.en.md, sites/x6-sites/docs/tutorial/basic/snapline.zh.md
=> docs: 📚️ add deprecation notice for Snapline.sharp

packages/x6/src/graph/renderer.ts
Close https://github.com/antvis/X6/issues/2487
=> fix: 🐛 not sort views after visible change

packages/x6/src/graph/view.ts, packages/x6/src/style/index.less
1、解决点击画布时，input无法正常失去焦点
2、添加touch-action: none;阻止移动端中滑动节点页面一起移动
3、https://github.com/antvis/X6/issues/2527
=> fix: 🐛  fix some issues

examples/x6-example-features/package.json, examples/x6-example-features/src/pages/bus/index.tsx, examples/x6-example-features/src/pages/bus/shapes.ts, examples/x6-example-features/src/pages/index.tsx, lerna.json, package.json, packages/x6-common/package.json, packages/x6-common/src/dom/event/core.ts, packages/x6-common/src/dom/event/special.ts, packages/x6-common/src/dom/event/util.ts, packages/x6-core/package.json, packages/x6-geometry/package.json, packages/x6-next/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json, yarn.lock
support mouseenter and mouseleave event
=> feat: support mouseenter and mouseleave event

examples/x6-example-features/src/pages/index.tsx, packages/x6-next/src/version.ts, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json, yarn.lock
=> chore: update x6-next version

examples/x6-app-dag/package.json, examples/x6-app-er/package.json, package.json, packages/x6-common/LICENSE, packages/x6-common/package.json, packages/x6-core/LICENSE, packages/x6-core/package.json, packages/x6-geometry/LICENSE, packages/x6-geometry/package.json, packages/x6-next/LICENSE, packages/x6-next/package.json, packages/x6-react-components/LICENSE, packages/x6-react-components/package.json, packages/x6-react-shape/LICENSE, packages/x6-react-shape/package.json, packages/x6-vue-shape/LICENSE, packages/x6-vue-shape/package.json
=> chore: 🔧 change publish script

packages/x6/src/addon/scroller/index.ts, sites/x6-sites/docs/api/graph/scroller.en.md, sites/x6-sites/docs/api/graph/scroller.zh.md
=> feat: ✨ support scroller resize direction

packages/x6-vue-shape/src/registry.ts, packages/x6-vue-shape/src/teleport.ts, packages/x6-vue-shape/src/view.ts, sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
=> refactor: ♻️ refactor x6 vue shape. close #2566

examples/x6-example-features/src/pages/react/extends.tsx, examples/x6-example-features/src/pages/react/portal.tsx, packages/x6-react-shape/src/registry.ts
=> feat: ✨ support inherit options for react-shape registry

examples/x6-example-features/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json
=> chore: 🔧 update peerdeps for some package

packages/x6/src/registry/tool/button.ts
support percent in edge button tool
=> fix: 🐛 support percent in edge button tool

packages/x6/src/registry/tool/editor.ts
Tools's update method is called every time an edge attribute is updated, so replace the update method with a name to avoid multiple invalid calls.
=> fix: 🐛 change the update function name to avoid unnecessary updates

packages/x6/src/style/raw.ts
=> fix: 🐛 update style

configs/package-json/cli.json, examples/x6-example-features/package.json, package.json, packages/x6-vue-shape/package.json, packages/x6/package.json, packages/x6/src/global/version.ts
=> chore: 🔧 add publish cmd

package.json, packages/x6-core/package.json, packages/x6-next/src/graph/options.ts, packages/x6-next/src/version.ts, packages/x6-next/src/view/node.ts, packages/x6-vector/package.json, yarn.lock
=> feat: add onPortRendered options

README.en-us.md, README.md, sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/about.zh.md, sites/x6-sites/docs/tutorial/contact.en.md, sites/x6-sites/docs/tutorial/contact.zh.md
=> docs: 📚️ add qrcode for communication

lerna.json, packages/x6-plugin-scroller/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json
=> chore: 🔧 update peerDeps for plugins

packages/x6-next/src/version.ts, yarn.lock
=> chore: 🔧 update yarn.lock

configs/package-json/cli.json, packages/x6-common/package.json, packages/x6-core/package.json, packages/x6-geometry/package.json, packages/x6-next/package.json, packages/x6-react-components/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json
=> chore: 🔧 remove release-it cmd

examples/x6-example-features/src/pages/keyboard/index.tsx, packages/x6-next/src/graph/graph.ts, packages/x6-plugin-keyboard/LICENSE, packages/x6-plugin-keyboard/README.md, packages/x6-plugin-keyboard/index.ts, packages/x6-plugin-keyboard/package.json, packages/x6-plugin-keyboard/rollup.config.js, packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-keyboard/tsconfig.json, yarn.lock
=> feat: ✨ add keyboard plugin

packages/x6/src/addon/dnd/index.ts, sites/x6-sites-demos/packages/tutorial/basic/dnd/dnd/src/app.tsx, sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
=> feat: ✨ dnd add options: dndContainer

packages/x6-plugin-scroller/src/scroller.ts
add trnsition methods for scroller plugin
=> feat: ✨ add trnsition methods for scroller plugin

packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-scroller/src/index.ts
=> fix: 🐛 change init method to public

packages/x6/src/addon/scroller/index.ts
Close https://github.com/antvis/X6/issues/2609
=> fix: 🐛 add page size check condition

examples/x6-example-features/src/pages/ports/connected.tsx, packages/x6-next/src/graph/graph.ts, packages/x6-next/src/graph/transform.ts, packages/x6-plugin-scroller/src/index.ts, packages/x6-plugin-scroller/src/scroller.ts
=> docs: 📚️ add port connected demo

sites/x6-sites/docs/tutorial/advanced/react.en.md, sites/x6-sites/docs/tutorial/advanced/react.zh.md
docs: fix the docs in use Vue3 Teleport
=> docs: fix the docs in use Vue3 Teleport

packages/x6-react-components/package.json, yarn.lock
update react-resize-detector version
=> chore: 🔧 update react-resize-detector version

packages/x6-vue-shape/README.md
=> docs: 📚️ update demo for readme

packages/x6-react-components/package.json, packages/x6-vue-shape/package.json, packages/x6/README.md, packages/x6/package.json, packages/x6/src/addon/scroller/index.ts, packages/x6/src/global/version.ts
=> fix: 🐛 fix scroller options typo

packages/x6-react-shape/src/view.ts, packages/x6/src/util/dom/elem.ts, packages/x6/src/view/node.ts
=> feat: ✨ foreignObject内部元素默认不触发拖动和选中行为 close #2549

packages/x6-react-components/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json, packages/x6/package.json, packages/x6/src/util/dom/attr.ts, packages/x6/src/view/attr.ts
add case sensitive attrs, related to https://github.com/antvis/X6/pull/2595
=> fix: 🐛 add case sensitive attrs

sites/x6-sites/docs/tutorial/basic/cell.en.md, sites/x6-sites/docs/tutorial/basic/dnd.en.md, sites/x6-sites/docs/tutorial/basic/node.en.md, sites/x6-sites/docs/tutorial/intermediate/attrs.en.md, sites/x6-sites/docs/tutorial/intermediate/custom-node.en.md
Translate some docs\tutorial\basic\*.md to english using deepl.com
Translate some docs\tutorial\basic .md to english using deepl.com
The en documatation is not translated from zh.
=> docs: 📚️ Translate some docs\tutorial\intermediate .md to english

sites/x6-sites/docs/tutorial/basic/background.en.md, sites/x6-sites/docs/tutorial/basic/background.zh.md
=> docs: 📚️ color not support gradients

sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/cell.zh.md, sites/x6-sites/docs/tutorial/basic/cell.zh.md
=> docs:修复中文文档关于zIndex描述中的错别字 修复 #2696

examples/x6-example-features/src/pages/selection/index.tsx, packages/x6-common/src/dom/elem.ts, packages/x6-common/src/dom/main.ts, packages/x6-common/src/dom/position.ts, packages/x6-plugin-scroller/src/index.ts, packages/x6-plugin-selection/LICENSE, packages/x6-plugin-selection/README.md, packages/x6-plugin-selection/index.ts, packages/x6-plugin-selection/package.json, packages/x6-plugin-selection/rollup.config.js, packages/x6-plugin-selection/scripts/style.js, packages/x6-plugin-selection/src/index.less, packages/x6-plugin-selection/src/index.ts, packages/x6-plugin-selection/src/selection.ts, packages/x6-plugin-selection/src/style/raw.ts, packages/x6-plugin-selection/tsconfig.json, packages/x6/src/graph/options.ts
=> feat: ✨ add selection plugin

packages/x6/src/addon/scroller/index.ts
#2408 添加 `direction` 后，之前的行为发生了变化，此 PR 部分修复了该问题。
resizeOptions 中提供了 useCellGeometry 设置，决定是否使用 model 计算尺寸。 #2408 中未使用此参数的值
=> fix: 🐛 add resizeOptions to getContentArea

examples/x6-example-features/src/pages/selection/index.tsx, package.json, packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-keyboard/src/keyboard.ts, packages/x6-plugin-scroller/src/index.ts, packages/x6-plugin-selection/src/index.ts
1. update publish script
2. expose the selection api
=> feat: ✨ expose the selection api

package.json
=> chore: 🔧 update publish script

lerna.json, package.json
=> chore: 🔧 updadte publish:beta script

sites/x6-svg-to-shape/package.json
remove test script for x6-svg-to-shape
=> chore: 🔧 remove test script for x6-svg-to-shape

lerna.json, package.json, packages/x6-common/package.json, packages/x6-plugin-keyboard/package.json, packages/x6-plugin-scroller/package.json, packages/x6-plugin-selection/package.json, packages/x6/package.json
=> chore: 🔧 revert version

package.json
=> chore: 🔧 change publish opts

packages/x6/src/util/platform/index.ts
Close https://github.com/antvis/X6/issues/2767
=> fix: 🐛 check if the navigator global is available before usage

examples/x6-example-features/src/pages/case/dag.tsx, packages/x6-plugin-selection/src/selection.ts
fix the error in selected nodes position when snapline enabled
=> fix: 🐛 fix the error in selected nodes position when snapline enabled

packages/x6/src/registry/router/manhattan/router.ts
add warn when use fallback router
=> fix: 🐛 add warn when use fallback router

packages/x6/src/graph/history.ts
fix the bug cannot read properties of null when cell is not exit
fix the bug cannot read properties of null when cell is not exit
=> fix:🐛fix the bug cannot read properties of null when cell is not exit

packages/x6/src/addon/selection/index.ts
Close https://github.com/antvis/X6/issues/2804
=> fix: 🐛 fix nodes moved error when snapped

sites/x6-sites/docs/api/model/node.en.md, sites/x6-sites/docs/api/model/node.zh.md
Close https://github.com/antvis/X6/issues/2801
=> docs: 📚️ add tips for insertPort api

examples/x6-example-features/src/pages/index.tsx, examples/x6-example-features/src/pages/stencil/index.tsx, packages/x6-plugin-stencil/LICENSE, packages/x6-plugin-stencil/README.md, packages/x6-plugin-stencil/package.json, packages/x6-plugin-stencil/rollup.config.js, packages/x6-plugin-stencil/scripts/style.js, packages/x6-plugin-stencil/src/grid.ts, packages/x6-plugin-stencil/src/index.less, packages/x6-plugin-stencil/src/index.ts, packages/x6-plugin-stencil/src/style/raw.ts, packages/x6-plugin-stencil/tsconfig.json, scripts/build-dev
=> feat: ✨ add stencil plugin

packages/x6-common/src/array/array.ts, packages/x6-common/src/dom/attr.ts, packages/x6-common/src/platform/index.ts, packages/x6-plugin-scroller/src/scroller.ts, packages/x6-react-components/package.json, packages/x6-vue-shape/package.json, packages/x6-vue-shape/src/view.ts, packages/x6/src/graph/mousewheel.ts, packages/x6/src/graph/options.ts, packages/x6/src/graph/view.ts, packages/x6/src/model/edge.ts, packages/x6/src/model/model.ts, packages/x6/src/registry/attr/connection.ts, packages/x6/src/registry/router/manhattan/obstacle-map.ts, packages/x6/src/registry/router/manhattan/options.ts, packages/x6/src/registry/router/manhattan/router.ts, packages/x6/src/registry/tool/button.ts, packages/x6/src/registry/tool/editor.ts, packages/x6/src/shape/base.ts, packages/x6/src/style/index.less, packages/x6/src/view/attr.ts, packages/x6/src/view/edge.ts, packages/x6/src/view/node.ts
=> feat: sync some commit from v1

packages/x6/src/view/tool.ts
=> fix: Cannot use "this" here: #2824

packages/x6/src/util/dom/geom.ts
add timeout for animation setup
=> fix: 🐛 add timeout for animation setup

packages/x6/src/renderer/queueJob.ts, packages/x6/src/renderer/scheduler.ts, packages/x6/src/shape/html.ts
sync render when change position
=> fix: sync render when change position

examples/x6-example-features/src/pages/scroller/index.tsx, packages/x6-plugin-clipboard/src/api.ts, packages/x6-plugin-clipboard/src/index.ts, packages/x6-plugin-export/src/api.ts, packages/x6-plugin-export/src/index.ts, packages/x6-plugin-history/src/api.ts, packages/x6-plugin-history/src/index.ts, packages/x6-plugin-keyboard/src/api.ts, packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-selection/src/api.ts, packages/x6-plugin-selection/src/index.ts, packages/x6-plugin-snapline/src/api.ts, packages/x6-plugin-snapline/src/index.ts, packages/x6-plugin-transform/src/api.ts, packages/x6-plugin-transform/src/index.ts
attach plugin api and events to grpah instance
=> feat: attach plugin api and events to grpah instance

sites/x6-sites/docs/api/graph/model.en.md, sites/x6-sites/docs/api/graph/model.zh.md
docs: function 'addCells()' is undefined. (#2823)
=> docs: function 'addCells()' is undefined. (#2823)

packages/x6-react-components/src/color-picker/index.tsx
fix: 🐛 fix typo for color-picker
=> fix: 🐛 fix typo for color-picker

packages/x6-plugin-scroller/package.json, packages/x6-plugin-scroller/src/scroller.ts, packages/x6/package.json
resize graph when scale scroller
=> fix: resize graph when scale scroller

packages/x6-plugin-dnd/package.json, packages/x6-plugin-dnd/src/index.ts, packages/x6-plugin-snapline/package.json, packages/x6-plugin-snapline/src/index.ts, sites/x6-sites-demos/packages/tutorial/plugins/dnd/dnd/package.json, sites/x6-sites-demos/packages/tutorial/plugins/dnd/dnd/src/app.css, sites/x6-sites-demos/packages/tutorial/plugins/dnd/dnd/src/app.tsx, sites/x6-sites-demos/packages/tutorial/plugins/dnd/stencil/package.json, sites/x6-sites-demos/packages/tutorial/plugins/dnd/stencil/src/app.css, sites/x6-sites-demos/packages/tutorial/plugins/dnd/stencil/src/app.tsx, sites/x6-sites-demos/packages/tutorial/plugins/minimap/playground/package.json, sites/x6-sites-demos/packages/tutorial/plugins/scroller/playground/package.json, sites/x6-sites-demos/packages/tutorial/plugins/snapline/playground/package.json
export snap methods from snapline
=> fix: export snap methods from snapline

packages/x6-plugin-export/package.json, packages/x6-plugin-export/src/api.ts, packages/x6-plugin-export/src/index.ts
=> feat: add exportSVG methods

packages/x6-plugin-selection/src/selection.ts, packages/x6-plugin-snapline/src/snapline.ts, pnpm-workspace.yaml
Modify the semantics of filter in selection and snapline plugin,the definition of filter is the same as the definition of filter in javascript, which is to filter out selected nodes
=> fix: modify the semantics of filter

packages/x6-plugin-snapline/src/snapline.ts, packages/x6-react-components/package.json, packages/x6-vue-shape/package.json
updae react-resize-detector version to avoid duplicate react versions
=> fix: updae react-resize-detector version

packages/x6/src/graph/mousewheel.ts
Close https://github.com/antvis/X6/issues/2928
=> fix: get correct center when zoom

packages/x6-react-components/package.json
=> fix: update react type version

.github/workflows/release.yml, .releaserc, packages/x6-common/package.json, packages/x6-plugin-clipboard/package.json, packages/x6-plugin-dnd/package.json, packages/x6-plugin-history/package.json, packages/x6-plugin-keyboard/package.json, packages/x6-plugin-minimap/package.json, packages/x6-plugin-scroller/package.json, packages/x6-plugin-selection/package.json, packages/x6-plugin-snapline/package.json, packages/x6-plugin-stencil/package.json, packages/x6-plugin-transform/package.json, packages/x6-react-components/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json, packages/x6/package.json, packages/x6/src/model/edge.ts, packages/x6/src/renderer/queueJob.ts
=> chore: update package version

packages/x6-vue-shape/src/view.ts
=> fix: render vue shape in minimap with same cellid when using teleport

packages/x6-common/src/dom/data.ts
https://github.com/antvis/X6/pull/2940
=> fix: dom.data support custom object

packages/x6-plugin-transform/src/index.ts
Close https://github.com/antvis/X6/issues
=> fix: trigger transform knob after click node

README.md, packages/x6-plugin-transform/package.json
=> chore: update readme

karma.conf.js, packages/x6-plugin-keyboard/src/keyboard.ts
=> fix: not trigger keyboard event whith delete key in contenteditable elem

packages/x6-plugin-snapline/src/index.ts, packages/x6-plugin-snapline/src/snapline.ts, packages/x6-react-shape/src/view.ts, packages/x6/src/renderer/queueJob.ts
Close https://github.com/antvis/X6/issues/2967
=> fix: render react shape in dnd graph

packages/x6-plugin-export/src/api.ts
Close https://github.com/antvis/X6/issues/2973
=> fix: export toJpeg methods in export plugin

packages/x6-plugin-selection/src/selection.ts
=> chore: update wrong comment word

packages/x6-common/package.json, packages/x6-plugin-selection/src/index.ts, packages/x6-plugin-selection/src/selection.ts, packages/x6-react-shape/package.json, packages/x6-react-shape/src/view.ts
Close https://github.com/antvis/X6/issues/2987 https://github.com/antvis/X6/issues/2955
=> fix: use geometry in selection box

.gitignore, package.json
=> chore: add eslintcache

packages/x6-plugin-selection/package.json
=> chore: release @antv/x6-plugin-selection@2.1.5

packages/x6/src/model/model.ts, packages/x6/src/renderer/scheduler.ts
Close https://github.com/antvis/X6/issues/2999
=> fix: hide elems when visible is false

examples/x6-example-features/src/pages/selection/index.tsx, packages/x6-plugin-transform/src/index.ts
Close https://github.com/antvis/X6/issues/2985
=> fix: make resizing options take effect

packages/x6/src/graph/graph.ts, packages/x6/src/graph/view.ts
Close https://github.com/antvis/X6/issues/3012 https://github.com/antvis/X6/issues/3013
=> fix: trigger preventDefault by origin event

packages/x6-vue-shape/src/view.ts
=> fix: cannot read properties of undefined when unmount vue component

packages/x6-plugin-scroller/package.json, packages/x6-plugin-scroller/src/scroller.ts
Close https://github.com/antvis/X6/issues/3016
=> fix: cancel debounce update for scroller plugin

package.json
update build:watch script base on https://github.com/bubkoo/run-shared-scripts
=> chore: update build:watch script

packages/x6/src/registry/tool/editor.ts
edit status char ghosting.
clear display value when edit status because char ghosting.
=> fix: :bug: char ghosting when edit text (#2560)

packages/x6/src/registry/router/manhattan/options.ts, packages/x6/src/view/node.ts
Close https://github.com/antvis/X6/issues/3056
=> fix: set snapToGrid to false by default

packages/x6-common/src/polyfill/index.ts
Close https://github.com/antvis/X6/issues/3068
=> fix: fix window incompatibility problem

packages/x6/src/registry/router/manhattan/options.ts, packages/x6/src/registry/router/manhattan/router.ts
=> fix: optimize snapToGrid options for manhattan

packages/x6-react-shape/src/view.ts, packages/x6-vue-shape/src/teleport.ts, packages/x6-vue-shape/src/view.ts
=> fix: add getGraph provide

packages/x6/src/graph/options.ts, packages/x6/src/renderer/scheduler.ts, sites/x6-sites/docs/api/graph/graph.zh.md, sites/x6-sites/docs/api/graph/view.zh.md, sites/x6-sites/docs/api/interacting/interaction.zh.md
Close https://github.com/antvis/X6/issues/3051
=> fix: add createView options

packages/x6-vue-shape/src/view.ts
=> fix: get graph from right place

packages/x6/src/renderer/scheduler.ts, sites/x6-sites/docs/api/graph/graph.zh.md
Close https://github.com/antvis/X6/issues/3053
=> fix: schedule edge when source and target is not ready

packages/x6-plugin-transform/src/transform.ts
Close https://github.com/antvis/X6/issues/3073
=> fix: add defense for view in transform plugin

packages/x6/src/renderer/scheduler.ts, sites/x6-sites/.dumi/global.ts, sites/x6-sites/docs/tutorial/about.zh.md, sites/x6-sites/examples/showcase/practices/demo/dataProcessingDag.tsx, sites/x6-sites/package.json
Close https://github.com/antvis/X6/issues/3097
=> fix: optimize rendering logic to prevent loops

sites/x6-sites/LEGAL.md, sites/x6-sites/package.json
=> docs: add LEGAL for sites

packages/x6/src/view/node.ts, sites/x6-sites/package.json
update group even group is empty
=> fix: update group even group is empty

packages/x6-plugin-dnd/src/index.ts, sites/x6-sites/docs/tutorial/plugins/dnd.zh.md
Close https://github.com/antvis/X6/issues/3132
=> fix: change dragging container options

examples/x6-example-features/src/pages/case/mind.tsx
close #3138 
mindmap实例使用了resetCells，如果节点为react/vue自定义节点，或者节点数量多的时候，会有性能问题
=> refactor: mindmap demo remove resetCells

examples/x6-example-features/src/pages/case/mind.tsx
当配置`async: false`的时候，`traverse`函数创建边会失败，需要先遍历子节点生成节点，再创建边
=> fix(mindmap demo): can not find target id when create edge

packages/x6-react-components/src/menubar/item.tsx
Close https://github.com/antvis/X6/issues/3143
=> fix: stop propagation when click menu item

packages/x6-common/src/css-loader/loader.ts
Close https://github.com/antvis/X6/issues/3125
=> fix: optimize css loader

packages/x6/src/renderer/scheduler.ts
Close https://github.com/antvis/X6/issues/3130
=> refactor: refactor cell remove schedule

packages/x6/src/graph/graph.ts
使用find代替forEach可以减少循环次数
- [ ✓] Code style optimization (changes that do not affect the meaning of the code)
- [✓] My code follows the code style of this project.
- [✓] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
=> chore: use find to repalce forEach

packages/x6/src/view/edge.ts, sites/x6-sites/docs/tutorial/plugins/selection.zh.md
Close https://github.com/antvis/X6/issues/2853
=> fix: prevent highlighting new edge

packages/x6-react-components/src/color-picker/index.tsx
Close https://github.com/antvis/X6/issues/2662
=> fix: don't hide when click on color picker

sites/x6-sites/gatsby-config.js
Close https://github.com/antvis/X6/issues/2227
=> docs: 📚️ show corrected demos in gallery

packages/x6/src/common/algorithm/priorityqueue.ts
Close https://github.com/antvis/X6/issues/2436 for v1.
=> fix: 🐛 fix index error for priorityQueue

packages/x6/package.json
=> chore: 🔧 release new version

packages/x6/src/view/node.ts, sites/x6-sites/docs/tutorial/basic/events.zh.md
Close https://github.com/antvis/X6/issues/2447
=> feat: add port events

packages/x6/src/addon/dnd/index.ts, sites/x6-sites/docs/tutorial/basic/dnd.zh.md
Link #3132
Pick commit 7b3e39ac72e552f6381076a37056c0b1eefad7b2 applied to v1 branch
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix(dnd): change dragging container options

packages/x6-plugin-clipboard/src/api.ts, packages/x6-plugin-clipboard/src/clipboard.ts, packages/x6-plugin-clipboard/src/index.ts
Close https://github.com/antvis/X6/issues/2573
=> fix: get correct clipboard content when useLocalStorage enabed

packages/x6-plugin-scroller/src/scroller.ts
Close https://github.com/antvis/X6/issues/3133
=> fix: clear old background when background enabled in background

packages/x6-plugin-scroller/src/index.ts, packages/x6-plugin-scroller/src/scroller.ts, sites/x6-sites/examples/showcase/practices/demo/flowchart.ts, sites/x6-sites/package.json
Close https://github.com/antvis/X6/issues/3152 https://github.com/antvis/X6/issues/3188
=> fix: set correct scroller options

packages/x6/src/shape/html.ts
Close https://github.com/antvis/X6/issues/3182
=> fix: ensure the container in html view

packages/x6/src/registry/router/manhattan/obstacle-map.ts, packages/x6/src/registry/router/manhattan/options.ts
=> fix: 🐛 change execludeNodes typo

examples/x6-example-features/src/pages/keyboard/index.tsx, packages/x6-plugin-clipboard/src/index.ts, packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-selection/src/index.ts, packages/x6-plugin-snapline/src/index.ts, packages/x6-plugin-transform/src/index.ts, packages/x6/src/graph/graph.ts
https://github.com/antvis/X6/issues/3142
增加disable和enable能力
- [✅] New feature (non-breaking change which adds functionality)
=> Feat plugins dis and en

packages/x6/src/renderer/scheduler.ts
Hey, 
This console.log ended up in production build, not sure it was on purpose.
=> fix(scheduler): remove spammy console.log

packages/x6-plugin-keyboard/src/api.ts, packages/x6-plugin-keyboard/src/index.ts, packages/x6-plugin-keyboard/src/keyboard.ts, sites/x6-sites/docs/tutorial/plugins/keyboard.zh.md
keyboard支持手动清空和手动触发
- [✅] New feature (non-breaking change which adds functionality)
=> feat: keyboard support clear and custom trigger

packages/x6/src/graph/graph.ts
Close https://github.com/antvis/X6/issues/3201
=> feat: add options for positionCell api

packages/x6-plugin-keyboard/src/keyboard.ts
=> chore: should use local to format

packages/x6-plugin-scroller/package.json, packages/x6-plugin-scroller/src/index.ts, sites/x6-sites/package.json
=> fix: fix scroller options typo

packages/x6/src/graph/graph.ts
Close https://github.com/antvis/X6/issues/3134
=> fix: add padding options for position api

packages/x6-common/src/dom/text.ts
Close https://github.com/antvis/X6/issues/3231 
Refer https://github.com/antvis/X6/discussions/3205#discussioncomment-4916606
=> fix: donot empty text when only has title elem

packages/x6/src/model/model.ts
=> feat: add updateNode/updateEdge API #3235

examples/x6-example-features/src/pages/history/index.tsx, examples/x6-example-features/src/pages/index.tsx, packages/x6-plugin-history/src/index.ts
history增加最大栈
- [✅] New feature (non-breaking change which adds functionality)
=> feat: history add max stack size

sites/x6-sites/docs/tutorial/plugins/history.zh.md
history 插件增加了 stackSize 的属性配置没有补齐文档
- [✅ ] Docs (changes that only update documentation)
=> docs: history插件文档补充stackSize属性的说明

packages/x6-common/src/dom/event/types.ts
Close https://github.com/antvis/X6/issues/3245
=> fix: fix typo for dom event handlers

examples/x6-example-features/src/pages/case/mind.tsx
=> fix: mindmap demo duplicate node id, close #3256

sites/x6-sites/docs/api/model/labels.zh.md
=> docs: fix typo in labels.zh.md

sites/x6-sites/docs/tutorial/plugins/stencil.md
=> docs: fix typo in stencil.md

sites/x6-sites/docs/tutorial/intermediate/custom-edge.en.md, sites/x6-sites/docs/tutorial/intermediate/custom-edge.zh.md, sites/x6-sites/docs/tutorial/intermediate/edge-labels.en.md, sites/x6-sites/docs/tutorial/intermediate/edge-labels.zh.md
=> docs: fix typo about ‘defaultLabel’ (v1)

packages/x6-common/src/function/function.ts, packages/x6/src/graph/virtual-render.ts, packages/x6/src/renderer/scheduler.ts
Close https://github.com/antvis/X6/issues/3240
=> fix: leading reset render area when init

packages/x6-common/package.json, packages/x6/package.json
=> chore: release 2 packages

sites/x6-sites/.dumirc.ts, sites/x6-sites/package.json
=> chore: change docsearch appid

packages/x6/src/renderer/scheduler.ts
=> fix: add judgment for edge view

packages/x6/package.json
=> chore: release x6@2.5.1

packages/x6-plugin-transform/src/transform.ts
transform active-handle类没有正确的被移除
- [✅] Bug fix (non-breaking change which fixes an issue)
=> fix: transform active-handle class should remove when active removed

sites/x6-sites/.dumirc.ts
=> docs: set version list to 2.x and 1.x

packages/x6/src/graph/events.ts, packages/x6/src/renderer/scheduler.ts
Close https://github.com/antvis/X6/issues/3085
=> feat: add view:mounted and view:unmounted event

packages/x6/src/registry/tool/editor.ts
=> fix: fix editor-tool for edge

README.en-us.md, README.md
=> chore: add awesome-x6 link

package.json
我看X6用的应该是Pnpm7的版本 应该在packjson中提示一下
否则6的某些版本会报错的，毕竟是pnpm大版本是breaking change
- [✅] Chore (changes that don't modify src or test files)
=> chore: should toast pnpm >= 7

sites/x6-sites/examples/edge/connector/demo/meta.json, sites/x6-sites/package.json
Close https://github.com/antvis/X6/issues/3290
=> docs: update screenshot for curve demo

sites/x6-sites/examples/showcase/practices/demo/orgchart.ts
Close https://github.com/antvis/X6/issues/3320
=> docs: remove freeze call

packages/x6/package.json, packages/x6/src/renderer/queueJob.ts, packages/x6/src/renderer/scheduler.ts
Close https://github.com/antvis/X6/issues/3304
=> fix: throw error when render edge without terminal

packages/x6-angular-shape/package.json, packages/x6-common/package.json, packages/x6-geometry/package.json, packages/x6-plugin-clipboard/package.json, packages/x6-plugin-dnd/package.json, packages/x6-plugin-export/package.json, packages/x6-plugin-history/package.json, packages/x6-plugin-keyboard/package.json, packages/x6-plugin-minimap/package.json, packages/x6-plugin-scroller/package.json, packages/x6-plugin-selection/package.json, packages/x6-plugin-snapline/package.json, packages/x6-plugin-stencil/package.json, packages/x6-plugin-transform/package.json, packages/x6-react-components/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json
Close https://github.com/antvis/X6/issues/3321
=> chore: add src to files

packages/x6/src/registry/router/manhattan/obstacle-map.ts, packages/x6/src/registry/router/manhattan/options.ts, sites/x6-sites/docs/api/registry/router.zh.md
Close https://github.com/antvis/X6/issues/3305
=> fix: add excludeShapes options for manhattan router

packages/x6/src/renderer/scheduler.ts
=> fix: reset all views when fromjson

packages/x6/package.json
=> chore: release 1 packages

packages/x6-angular-shape/package.json
=> chore: release 1 packages (x6-angular-shape)

packages/x6/src/renderer/scheduler.ts
修复内部调用resetViews报错 close #3351
=> fix: hotfix #3351 error when call resetViews

packages/x6/src/model/cell.ts, packages/x6/src/model/model.ts, packages/x6/src/registry/registry.ts, packages/x6/src/renderer/scheduler.ts, packages/x6/src/view/cell.ts, packages/x6/src/view/node.ts
使用Object.values/Object.entities替换Object.keys，代码更加精简，可读性更好
readme提到三个主流浏览器支持最新的2个版本，从[caniuse](https://caniuse.com/?search=object.values)的结果看，均是支持的。
=> refactor: using Object.values instead of Object.keys

examples/x6-example-features/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json, packages/x6/package.json, pnpm-lock.yaml
@antv/x6-react-shape@2.1.1
@antv/x6-vue-shape@2.0.10
@antv/x62.5.5
=> chore: release 3 packages

packages/x6-devtool/package.json, sites/x6-sites/docs/tutorial/intermediate/angular.md, sites/x6-sites/docs/tutorial/intermediate/react.zh.md, sites/x6-sites/docs/tutorial/intermediate/vue.md
=> fix: add dependencies for x6-devtools

sites/x6-sites/docs/tutorial/intermediate/angular.md, sites/x6-sites/docs/tutorial/intermediate/react.zh.md
=> docs: update warnning for x6-react-shape

examples/x6-example-features/package.json, pnpm-lock.yaml, sites/x6-sites/docs/tutorial/intermediate/vue.md
=> chore: remove corejs deps

packages/x6/src/registry/connector/jumpover.ts
Close https://github.com/antvis/X6/issues/3387
=> fix: add timeout to wait target node is connected

packages/x6/package.json
=> fix: x6 common deps

.github/workflows/ci.yml, .github/workflows/pr-label-status.yml, packages/x6/package.json
- release x6@2.5.6
- fix error params in github action yaml
=> chore: change workflow id names

packages/x6/src/view/node.ts
=> fix: parseint zindex to get correct max zindex node

package.json, packages/x6/src/registry/tool/button.ts, pnpm-lock.yaml, sites/x6-sites/docs/api/registry/edge-tool.zh.md, sites/x6-sites/docs/api/registry/node-tool.zh.md
=> docs: add some config for node-tool

sites/x6-sites/.dumirc.ts, sites/x6-sites/docs/tutorial/about.zh.md
=> chore: update docsearch api key

packages/x6/package.json
=> chore: release @antv/x6@2.9.1

packages/x6/src/graph/options.ts
=> fix: type of `moveThreshold` should be `number`

packages/x6-plugin-minimap/package.json, packages/x6-plugin-minimap/src/index.ts, packages/x6/package.json, packages/x6/src/graph/graph.ts, packages/x6/src/graph/options.ts, packages/x6/src/renderer/scheduler.ts, sites/x6-sites/src/tutorial/plugins/minimap/index.less, sites/x6-sites/src/tutorial/plugins/minimap/index.tsx, sites/x6-sites/src/tutorial/plugins/minimap/simple-view.tsx, sites/x6-sites/src/tutorial/plugins/scroller/index.less
=> feat: support render simple view in minimap

packages/x6/src/view/node.ts
Close https://github.com/antvis/X6/issues/3454
=> fix: fix error usage of parseInt

packages/x6/package.json, packages/x6/src/graph/options.ts, packages/x6/src/view/cell.ts, packages/x6/src/view/edge.ts, packages/x6/src/view/node.ts, sites/x6-sites/docs/api/interacting/interaction.zh.md, sites/x6-sites/docs/tutorial/basic/interacting.zh.md
Connection strategy is not the best solution, and it can cause code coupling. so remove it.
=> fix: remove connection strategy option

packages/x6/src/view/cell.ts
=> fix: remove unused type

sites/x6-sites/docs/api/registry/connection-point.zh.md, sites/x6-sites/docs/api/registry/node-anchor.zh.md
unified doc format
unified ConnectionPoint doc, NodeAnchor doc
=> docs: unified doc format

sites/x6-sites/docs/tutorial/plugins/transform.zh.md, sites/x6-sites/src/tutorial/plugins/transform/resizing/index.tsx, sites/x6-sites/src/tutorial/plugins/transform/resizing/settings.tsx
Close https://github.com/antvis/X6/issues/3493
=> docs: restricted => restrict

examples/x6-example-features/src/pages/basic/index.tsx, packages/x6-angular-shape/package.json, packages/x6-common/package.json, packages/x6-geometry/package.json, packages/x6-plugin-clipboard/package.json, packages/x6-plugin-dnd/package.json, packages/x6-plugin-export/package.json, packages/x6-plugin-history/package.json, packages/x6-plugin-keyboard/package.json, packages/x6-plugin-minimap/package.json, packages/x6-plugin-scroller/package.json, packages/x6-plugin-selection/package.json, packages/x6-plugin-snapline/package.json, packages/x6-plugin-stencil/package.json, packages/x6-plugin-transform/package.json, packages/x6-react-components/package.json, packages/x6-react-shape/package.json, packages/x6-vue-shape/package.json, packages/x6/package.json, pnpm-lock.yaml
=> chore: release some packages

packages/x6-plugin-selection/src/index.less, packages/x6/src/registry/tool/editor.ts
Close https://github.com/antvis/X6/issues/3488 https://github.com/antvis/X6/issues/3497
=> fix: remove editor before added

packages/x6-plugin-selection/package.json, packages/x6/package.json
=> chore: release x6@2.9.7 and selection@2.1.7

sites/x6-sites/docs/api/model/marker.zh.md
Util.normalizeMarker -> Registry.Marker.normalize
refer to https://github.com/antvis/X6/blob/ea01b1d3eb27bc5d0ba91a8ff9723d603623efc8/packages/x6/src/registry/marker/util.ts#L7
=> docs: Update marker.zh.md

packages/x6-devtool/devtools/manifest.json
=> feat: change manifest for submit to chrome web store

packages/x6-plugin-history/src/index.ts
=> fix: undo crash when attr is null

packages/x6-plugin-history/package.json, packages/x6/package.json, packages/x6/src/registry/tool/editor.ts
Close https://github.com/antvis/X6/issues/3575 https://github.com/antvis/X6/issues/3559
=> fix: trigger dblclick event only one time

sites/x6-sites/docs/api/model/attrs.zh.md, sites/x6-sites/docs/api/model/cell.zh.md, sites/x6-sites/docs/tutorial/basic/node.zh.md, sites/x6-sites/docs/tutorial/basic/serialization.zh.md, sites/x6-sites/docs/tutorial/plugins/dnd.zh.md
=> docs: optimize doc for cell

packages/x6/src/registry/tool/editor.ts, sites/x6-sites/docs/api/registry/edge-tool.zh.md, sites/x6-sites/docs/api/registry/node-tool.zh.md
Close https://github.com/antvis/X6/issues/3546
=> fix: setText and getText support string

packages/x6-react-shape/src/view.ts
=> fix: same cell id when using portal #2949

examples/x6-example-features/src/pages/basic/index.tsx, sites/x6-sites/docs/api/model/cell.zh.md
=> docs: optimize cell.md

packages/x6-react-shape/package.json, packages/x6/package.json
chore: release x6@2.11.1 and x6-react-shape@2.2.2
=> chore: release x6@2.11.1 and x6-react-shape@2.2.2

packages/x6/src/style/index.less
=> fix: widget ouside graph, close #3595

sites/x6-sites/.dumirc.ts
=> Update .dumirc.ts 统一官网消息配置，合并后官网发个版

packages/x6-common/src/dom/text.ts
Close https://github.com/antvis/X6/issues/3635
=> fix: replace children prop to childNodes

sites/x6-sites/docs/api/graph/panning.zh.md
=> docs: typo fix

sites/x6-sites/site/pages/index.zh.tsx
=> docs: fixed the link to the homepage of the official website (#3651)

sites/x6-sites/docs/api/model/cell.zh.md, sites/x6-sites/docs/api/model/edge.zh.md, sites/x6-sites/docs/api/model/node.zh.md
=> docs: optimize docs for model

packages/x6/src/graph/mousewheel.ts
Close https://github.com/antvis/X6/issues/3655
=> fix: reset factor when calc factor is 1

scripts/run-test
=> chore: format scripts

sites/x6-sites/docs/tutorial/plugins/scroller.zh.md
Description
在 文档-插件-滚动画布 处添加了与画布panning配置冲突的相关说明
=> docs: Add notes in the scroller plugin doc

packages/x6-common/src/dom/event/object.ts, packages/x6-plugin-stencil/package.json, packages/x6/src/view/view.ts
Close https://github.com/antvis/X6/issues/3697
=> fix: set some function to own attrs

packages/x6/src/renderer/scheduler.ts, packages/x6/src/view/edge.ts
Close https://github.com/antvis/X6/issues/3668
=> fix: render edge when source or target in render area

sites/x6-sites/docs/tutorial/basic/graph.zh.md
=> docs: modify the sample style error

packages/x6/src/renderer/queueJob.ts
change update prioriy in render
=> fix: change update prioriy in render

packages/x6-plugin-scroller/package.json, packages/x6/package.json, packages/x6/src/registry/tool/vertices.ts
Close https://github.com/antvis/X6/issues/3327
=> fix: fix invalid history on vertices tool

packages/x6-plugin-dnd/src/index.ts, packages/x6-plugin-stencil/src/index.ts, sites/x6-sites/docs/tutorial/plugins/stencil.md, sites/x6-sites/src/tutorial/plugins/stencil/index.less, sites/x6-sites/src/tutorial/plugins/stencil/index.tsx
Close https://github.com/antvis/X6/issues/2568
Close https://github.com/antvis/X6/issues/3425
Close https://github.com/antvis/X6/issues/3427
Close https://github.com/antvis/X6/issues/2512
=> feat: supports dynamic modification of groups and nodes in stencil

packages/x6/src/util/index.ts
Close https://github.com/antvis/X6/issues/3228
=> fix: consider transform when calc bbox

packages/x6/src/model/edge.ts
Close https://github.com/antvis/X6/issues/2631
=> fix: unembed edge only when have new parent

packages/x6/src/graph/mousewheel.ts, sites/x6-sites/docs/api/graph/mousewheel.zh.md
修正 mousewheel 的 guard 参数，使其符合类型
=> fix: guard parameter does not match the type

packages/x6/src/renderer/scheduler.ts
Close https://github.com/antvis/X6/issues/3768
=> fix: sync render tools

sites/x6-sites/docs/tutorial/plugins/export.zh.md
=> feat: 修改文档错别字

sites/x6-sites/package.json
Close https://github.com/antvis/X6/issues/3789
=> docs: update antd version

packages/x6/src/model/model.ts
When the new and old Id are the same and this API is also called, the cell will disappear
https://codesandbox.io/s/mo-ban-forked-xxcx2s?file=/src/App.tsx
=> fix: updateCellId api bug

packages/x6-angular-shape/src/view.ts
=> fix: 修复 Angular Component 节点被移除时没有触发销毁的生命周期

packages/x6/src/registry/tool/editor.ts
https://github.com/antvis/X6/issues/3698#issuecomment-1661400255
https://github.com/antvis/X6/issues/3820
=> feat: node-editor新增width和height配置

sites/x6-sites/docs/tutorial/plugins/history.zh.md
=> fix: doc incorrect text

packages/x6/src/util/index.ts
Close https://github.com/antvis/X6/issues/3867
Close https://github.com/antvis/X6/issues/3830
=> fix: not consider transform when get bbox

package.json
"pnpm run build:watch" 在macos中正常运行, 在windows下无法正常运行.
=> fix: "pnpm run build:watch" 在windows下无法正常运行

packages/x6/src/registry/tool/vertices.ts
ref:https://github.com/antvis/X6/issues/3728
=> fix: trigger click event when click edge with vertices tool

packages/x6-plugin-dnd/src/index.ts
=> fix: plugin-dnd horizontal scroll compatibility (#3912)

packages/x6-plugin-selection/src/selection.ts
=> fix: plugin-selection unmatch after scale graph (#3907)

packages/x6/src/view/cell.ts
Close https://github.com/antvis/X6/issues/3931
=> fix: judge interacting after remove tools

packages/x6-plugin-transform/src/transform.ts
ref: https://github.com/antvis/X6/issues/3930
=> fix: stop listener event when transform dispose

packages/x6-plugin-history/src/index.ts
Close https://github.com/antvis/X6/issues/3937
=> fix: recoginze dirty flag on undefined attr

packages/x6-plugin-dnd/src/index.ts
Close https://github.com/antvis/X6/issues/3873
=> fix: subtract draggingContainer offset when position

packages/x6/src/registry/router/manhattan/obstacle-map.ts, packages/x6/src/registry/tool/editor.ts
Close https://github.com/antvis/X6/issues/3860 https://github.com/antvis/X6/issues/3957 https://github.com/antvis/X6/issues/3869
=> fix: support cancel editor no mobile

packages/x6/src/view/view.ts
=> fix: don't dispose graph view

packages/x6-plugin-selection/src/api.ts
=> fix: delete return selection

packages/x6/src/graph/panning.ts
开启 panning 之后，对 mousewheel 事件增加 eventTypes 判断，如果 panning 插件无法处理则允许事件继续冒泡传播
目前开启 panning 之后鼠标放在 graph 区域滚动会被捕获，无法触发外部容器的滚动
=> fix: paning mousewheel

sites/x6-sites/.dumirc.ts, sites/x6-sites/package.json
=> docs: iamge position change

package.json, packages/x6-plugin-stencil/src/index.ts, pnpm-lock.yaml
Close https://github.com/antvis/X6/issues/4007
Ref https://github.com/antvis/X6/pull/4066
=> fix: bind dragstart after add group

sites/x6-sites/docs/api/graph/graph.zh.md
=> docs: fix the container name

packages/x6-plugin-keyboard/src/keyboard.ts
fix #4065 , Keyboard插件绑定上下左右几个箭头事件的时候，回调函数里使用return false也不能阻止浏览器默认事件，看了[Mousetrap文档](https://craig.is/killing/mice)说这几个方向键对应的key是up right down left, 而浏览器原生事件里的code是ArrowUp ArrowRight  ArrowDown  ArrowLeft, 所以修改了keyboard.ts的 formatkey 方法，把这几个key转成Mousetrap需要的格式
=> fix: format keyboard arrow codes to Mousetrap special codes (#4065)

packages/x6-vue-shape/src/teleport.ts
Direct import `markRaw`, `Fragment` and `Teleport` from `vue-demi`
fix #4096
=> fix(vue-shape): remove deprecated `Vue` from import

packages/x6/src/registry/node-anchor/orth.ts
Close https://github.com/antvis/X6/issues/4123
=> fix:node-anchor的orth锚点，angle为负值导致数值计算为无穷

packages/x6/src/graph/options.ts
=> fix: snap anchor should be optional

packages/x6-react-shape/src/view.ts
add key for portal to avoid rerender
=> fix: add key for portal to avoid rerender

sites/x6-sites/docs/tutorial/plugins/dnd.zh.md, sites/x6-sites/docs/tutorial/plugins/stencil.md
https://github.com/antvis/X6/issues/4127#issuecomment-1950982571
=> docs: remove deprecated `Addon` usage

packages/x6-plugin-export/src/index.ts
=> fix: plugin-export API exportjpeg exports are PNG images

sites/x6-sites/docs/api/registry/router.zh.md
=> docs: manhattan fallbackRouter options

packages/x6-angular-shape/src/view.ts
https://github.com/Eve-Sama/x6-angular-shape/issues/1
=> fix: 修复 Angular 组件内部无法使用外部服务的问题

.gitignore, packages/x6-react-components/src/util/dom/MouseMoveTracker.ts, packages/x6-react-components/src/util/dom/animationFrame.ts, packages/x6-react-components/src/util/dom/executionEnvironment.ts, pnpm-lock.yaml, sites/x6-sites/.dumi/global.ts, sites/x6-sites/.dumirc.ts, sites/x6-sites/.gitignore, sites/x6-sites/mako.config.json, sites/x6-sites/package.json
@antv/x6-react-components
x6-sites
=> docs: update dumi configurations to optimize site SEO

sites/x6-sites/docs/api/graph/graph.en.md, sites/x6-sites/docs/api/graph/grid.en.md, sites/x6-sites/docs/api/graph/grid.zh.md, sites/x6-sites/docs/api/model/attrs.en.md, sites/x6-sites/docs/api/model/cell.en.md, sites/x6-sites/docs/api/model/edge.en.md, sites/x6-sites/docs/api/model/interaction.en.md, sites/x6-sites/docs/api/model/labels.en.md, sites/x6-sites/docs/api/model/marker.en.md, sites/x6-sites/docs/api/model/node.en.md, sites/x6-sites/docs/api/mvc/model.en.md, sites/x6-sites/docs/api/registry/edge-anchor.en.md, sites/x6-sites/docs/api/registry/filter.en.md, sites/x6-sites/docs/api/registry/node-anchor.en.md, sites/x6-sites/docs/api/registry/router.en.md, sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/basic/edge.en.md, sites/x6-sites/docs/tutorial/basic/graph.en.md, sites/x6-sites/docs/tutorial/basic/interacting.en.md, sites/x6-sites/docs/tutorial/basic/node.en.md, sites/x6-sites/docs/tutorial/basic/port.en.md, sites/x6-sites/docs/tutorial/getting-started.en.md, sites/x6-sites/docs/tutorial/intermediate/connection-point.en.md, sites/x6-sites/docs/tutorial/intermediate/group.en.md, sites/x6-sites/docs/tutorial/intermediate/tools.en.md, sites/x6-sites/docs/tutorial/update.en.md
1. 修复英文文档中链接跳转到中文文档的问题
2. 修改遗漏的中文文档中链接404的问题
相关
#4654 #4659
刚刚提的pr #4663 因为分支命名的问题关闭了
=> docs: 修复英文文档跳转错误的问题

sites/x6-sites/docs/tutorial/about.en.md, sites/x6-sites/docs/tutorial/about.zh.md
=> chore: update dingtalk group qrcode

packages/x6-plugin-export/src/index.ts
- fixed https://github.com/antvis/X6/issues/4665 
参考issue的问题描述以及原因和解决方法
before:
after:
=> fix:  `exportPNG` not display image markup

sites/x6-sites/docs/tutorial/about.zh.md, sites/x6-sites/docs/tutorial/basic/edge.zh.md, sites/x6-sites/docs/tutorial/basic/graph.zh.md, sites/x6-sites/docs/tutorial/basic/interacting.zh.md, sites/x6-sites/docs/tutorial/basic/node.zh.md, sites/x6-sites/docs/tutorial/basic/port.zh.md, sites/x6-sites/docs/tutorial/getting-started.zh.md, sites/x6-sites/docs/tutorial/intermediate/connection-point.zh.md, sites/x6-sites/docs/tutorial/intermediate/group.zh.md, sites/x6-sites/docs/tutorial/intermediate/tools.zh.md, sites/x6-sites/docs/tutorial/update.zh.md
修复了文档中所有跳转链接404的问题
用户使用文档查阅时，本想点击链接查看指定的详细内容，但是会直接404页面，影响使用且会让人觉得x6文档不专业
=> docs: fix tutorial links invalid

.github/workflows/gh-pages.yml, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, sites/x6-sites/package.json
=> chore: add gh-pages actions

.github/workflows/gh-pages.yml, sites/x6-sites/.dumirc.ts, sites/x6-sites/examples/showcase/practices/index.en.md
=> chore: show language switcher

.github/workflows/gh-pages.yml
=> chore: update checkout actions version

.github/workflows/gh-pages.yml
=> fix: site actions

.github/workflows/ci.yml, .github/workflows/gh-pages.yml
站点部署的 action，应该是在合并到 master 之后才触发，而不是每一个 pr。
=> fix: do not exec gh-pages deploy on pull_request

.github/workflows/manage-labeled.yml, .github/workflows/sync-issue-label.yml
update github action to add `oscp` by using https://github.com/antvis/github-config
=> Chore update GitHub action

packages/x6/src/graph/options.ts, sites/x6-sites/docs/api/graph/graph.en.md, sites/x6-sites/docs/api/graph/graph.zh.md, sites/x6-sites/docs/api/mvc/view.en.md, sites/x6-sites/docs/api/mvc/view.zh.md
- fixed https://github.com/antvis/X6/issues/4577
- 最终效果：https://github.com/antvis/X6/pull/4691
=> fix: 修正画布配置 onEdgeLabelRendered 类型使用问题并且完善文档说明

site/.dumirc.ts
=> fix: doc path in .dumirc.ts

site/docs/api/model/node.en.md, site/docs/api/model/node.zh.md
=> docs(node): 修正 setPortProp 方法的文档示例

.github/workflows/build.yml, README.en-us.md, README.md, __tests__/geometry/circle.spec.ts, biome.json, package.json, setup-env.ts, vitest.config.ts
=> chore: add coverage

__tests__/common/dom/matrix.test.ts, setup-env.ts, src/common/dom/matrix.ts
=> fix: dom matrix tests

.github/workflows/gh-pages.yml, __tests__/geometry/curve.spec.ts, __tests__/geometry/path/close.spec.ts, __tests__/geometry/path/curve-to.spec.ts, __tests__/geometry/path/line-to.spec.ts, __tests__/geometry/path/move-to.spec.ts, __tests__/geometry/path/path.spec.ts, __tests__/geometry/path/segment.spec.ts, __tests__/geometry/path/util.spec.ts, __tests__/geometry/util.spec.ts, src/geometry/path/util.ts
=> fix: add tests for geometry

__tests__/view/node/index.spec.ts
=> test: add test cases for view/node

__tests__/view/edge/index.spec.ts
=> test: add testcase for view/edge

__tests__/plugin/history-api.spec.ts, __tests__/plugin/history.spec.ts
=> test: add test cases for plugin-history

__tests__/plugin/snapline.spec.ts, __tests__/renderer/queueJob.spec.ts, __tests__/renderer/renderer.spec.ts, __tests__/renderer/scheduler.spec.ts
目前覆盖率：
大部分都是ai跑的，做了手动修正，越简单的文件看起来效果越好，像scheduler这种复杂些的写出来效果感觉很多case并不算特别好
=> test: add test case for renderer

README.en-us.md, README.md
=> chore: Update README.md

examples/package.json, examples/tsconfig.json
=> chore(examples): 修复 import @antv/x6 识别出现类型错误
